declare const _default: {
    _1: string;
    _2: string;
    _3: string;
    _4: string;
    _5: string;
    _6: string;
    _7: string;
    _8: string;
    _9: string;
    _10: string;
    _11: {
        bed: (_0: boolean) => string[];
        plushie: (_0: boolean) => string[];
        computer: (_0: boolean) => string[];
        flowers: (_0: boolean) => string[];
    };
    b_act: {
        agree: string;
        annoy: string;
        appease: string;
        bathe: string;
        beckon: string;
        blind: string;
        boast: string;
        bow: string;
        burn: string;
        challenge: string;
        check: string;
        cheer: string;
        clean: string;
        comfort: string;
        compliment: string;
        console: string;
        counter: string;
        create: string;
        criticize: string;
        dance: string;
        direct: string;
        disarm: string;
        disown: string;
        distance: string;
        ditch: string;
        dontpick: string;
        encourage: string;
        flash: string;
        flirt: string;
        grin: string;
        guide: string;
        handshake: string;
        heckle: string;
        heel: string;
        hug: string;
        hum: string;
        imitate: string;
        insult: string;
        joke: string;
        laugh: string;
        lecture: string;
        leech: string;
        mislead: string;
        mystify: string;
        pat: string;
        pay: string;
        perch: string;
        pet: string;
        pick: string;
        play: string;
        playdead: string;
        plead: string;
        poke: string;
        pose: string;
        praise: string;
        rap: string;
        reassure: string;
        resniff: string;
        roll: string;
        scream: string;
        secret: string;
        shove: string;
        sit: string;
        slap: string;
        spark: string;
        stare: string;
        steal: string;
        talk: string;
        taunt: string;
        telloff: string;
        terrorize: string;
        threat: string;
        translate: string;
        travel: string;
        tug: string;
        turn: string;
        upgrade: string;
        walk: string;
        whisper: string;
        whistle: string;
    };
    b_group_nobody: () => "* ...but everybody ran." | "* ...but nobody came.";
    b_opponent_dummy: {
        act_check: string[];
        act_flirt: string[];
        act_hug: string[];
        act_slap: string[];
        act_talk: string[];
        bored: string[];
        hugged: string[];
        name: string;
        slapped: string[];
        slapped2: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        talk: string[];
    };
    b_opponent_maddummy: {
        act_check: () => string[];
        act_flirt: () => string[];
        act_hug: () => string[];
        act_slap: () => string[];
        act_talk: () => string[];
        boredTalk: string[];
        changeStatus1: string[];
        changeStatus2: string[];
        fightFail: string[];
        fightFailStatus: string[];
        final1: () => string[];
        gladTalk1: string[];
        gladTalk2: string[];
        gladTalk3: string[];
        gladTalk4: string[];
        gladTalk5: string[];
        gladTalk6: string[];
        hugTalk1: () => string[];
        hugTalk2: () => string[];
        hugTalk3: () => string[];
        hugTalk4: string[];
        name: () => "* Glad Dummy" | "* Mad Dummy";
        phase2Talk1: string[];
        phase2Talk2: string[];
        phase2Talk3: string[];
        phase2Talk4: string[];
        phase2Talk5: string[];
        phase2Talk6: string[];
        phase2Talk7: string[];
        phase2Talk8: string[];
        phase3Talk1: string[];
        phase3Talk2: string[];
        phase3Talk3: string[];
        phase3Talk4: string[];
        phaseChange1: string[];
        phaseChange2a: string[];
        phaseChange2b1: string[];
        phaseChange2b2: string[];
        phaseChange2c: string[];
        phaseChange3a1: string[];
        phaseChange3a2: string[];
        phaseChange3b: string[];
        phaseChange3c1: string[];
        phaseChange3c2: string[];
        phaseChange3c3: string[];
        phaseChange3c4: string[];
        phaseChange3c5: string[];
        phaseChange3d: string[];
        phaseChange3e: string[];
        randStatus1: string[];
        randStatus2: string[];
        randStatus3: string[];
        randStatus4: string[];
        randStatus5: string[];
        randTalk1: string[];
        randTalk2: string[];
        randTalk3: string[];
        randTalk4: string[];
        slapTalk1: string[];
        slapTalk2: string[];
        slapTalk3: string[];
        slapTalk4: string[];
        status1: () => string[];
    };
    b_opponent_moldsmal: {
        act_check: () => string[];
        act_flirt: string[];
        act_imitate: string[];
        act_slap: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        name: string;
        perilStatus: string[];
        sexyChat: string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        status5: () => string[];
        status6: () => string[];
        status7: () => string[];
        status8: string[];
    };
    b_opponent_spacetop: {
        act_check: () => string[];
        act_compliment: string[];
        act_flirt: string[];
        complimentTalk1: string[];
        complimentTalk2: string[];
        createStatus1: () => string[];
        createStatus2: () => string[];
        createTalk1: string[];
        createTalk2: string[];
        createTalk3: string[];
        createTalk4: string[];
        createTalk5: string[];
        act_create: () => string[];
        flirtStatus1: string[];
        flirtStatus2: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        genoStatus: string[];
        hurtStatus: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        justiceTalk: string[];
        name: string;
        randStatus1: string[];
        randStatus2: string[];
        randStatus3: string[];
        randStatus4: string[];
        status1: string[];
        stealTalk1: string[];
        stealTalk2: string[];
        act_steal: () => string[];
    };
    b_opponent_space: {
        act_check: () => string[];
        act_reassure: string[];
        genoStatus: string[];
        happyStatus: string[];
        happyTalk1: string[];
        happyTalk2: string[];
        happyTalk3: string[];
        happyTalk4: string[];
        hurtStatus: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        name: string;
        randStatus1: string[];
        randStatus2: string[];
    };
    b_party_kidd: {
        mkDeath1: string[];
        mkDeath2: string[];
        mkDeath3: string[];
        mkDeath4: string[];
        mkDeath1OW: string[];
        mkDeath2OW: string[];
        mkDeath3OW: string[];
        mkDeath4OW: string[];
        mkMagic1: string[];
        mkMagic2a: string[];
        mkMagic2b: string[];
        mkMagic2c: string[];
        mkNope: string[];
        mkTurn1: string[];
        mkTurn2: string[];
        mkTurn3: string[];
        mkTurnAct1: string[];
        mkWeaken1: string[];
        mkWeaken2: string[];
        mkWeaken3a: string[];
        mkWeaken3b: string[];
        mkWeaken3c: string[];
        mkTurnActRand1: (opponent: string) => string[][];
        mkTurnActRand2: (opponent: string) => string[][];
        mkTurnActRand3: (opponent: string) => string[][];
        mkTurnActRand4: (opponent: string) => string[][];
        mkTurnActResult0: string[];
        mkTurnActResult1: (opponent: string) => string[];
        mkTurnActResult2: (opponent: string) => string[];
        mkTurnActResult3: (opponent: string, multiple: boolean) => string[];
        mkTurnActResult4: (opponent: string, multiple: boolean, allowpac: boolean) => string[];
        mkTurnFight1: string[];
        mkTurnFight2a: string[];
        mkTurnFight2b: string[];
        mkTurnFight3a: string[];
        mkTurnFight3b: string[];
        mkTurnFight3c: string[];
        mkTurnMercy1: string[];
        mkTurnX: string[];
    };
    c_call1: string;
    c_call2: string;
    c_nobody1: string[];
    c_nobody2: string[];
    c_nobody3: string[];
    c_nobody4: string[];
    c_nobody5: string[];
    i_water: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    x_credits: () => string[];
};
export default _default;
