declare const text: {
    a_foundry: {
        artifact1: string[];
        artifact2: string[];
        artifact3: string[];
        astrofood1: () => string[];
        astrofood2: string[];
        astrofood3: string[];
        astrofood4: () => string[];
        astrofood5: string[];
        bird1: string[];
        bird2: string[];
        blookdate1: () => string[];
        blookdate2: () => string[];
        blookdate2x: string[];
        blookdate3: string[];
        blookdate4a: string[];
        blookdate4b: string[];
        blookdate5: string[];
        blookdate6a: string[];
        blookdate6b: string[];
        blookdate7: string[];
        blookdate8: string[];
        blookdate8x: string[];
        blookdate9: string[];
        blookmusic1: () => string[];
        blookmusic1x: string[];
        blookmusic2: () => string[];
        blookmusic2x: () => string[];
        blookmusic3a: string[];
        blookmusic3b: string[];
        blookmusic3c: string[];
        blookmusic3d: string[];
        blooksnail1: (...args: any[]) => string[];
        blooksnail1i: string[];
        blooksnail2a: string[];
        blooksnail2b: string[];
        blooksnail2b0: string[];
        blooksnail3: string[];
        blooksnail3i: string[];
        blooksnail4a: string[];
        blooksnail4b: string[];
        blooksnail4c: string[];
        blooksnail4d: string[];
        blooksnail4e: string[];
        blooksnail4f: string[];
        blooksnailX: {
            a: string;
            b: string;
            c: string;
            d: string;
            e: string;
        };
        blooksorry1: string[];
        blooksorry2: string[];
        blooksorry3: string[];
        blooksorryX: string[];
        blooksorryY: string[];
        blooktouch1: () => string[];
        blooktouch2a1: string[];
        blooktouch2a2: string[];
        blooktouch2b1: string[];
        blooktouch2b2: string[];
        blooktouch2c1: string[];
        blooktouch2c2: string[];
        blooktouch2c2x: string[];
        blooktouch2c3a: string[];
        blooktouch2c3b: string[];
        blooktouch2c4: string[];
        blooktouch2c5a: string[];
        blooktouch2c5b: string[];
        blooktouch2d1: string[];
        blooktouch2d2: string[];
        blookyard1: () => string[];
        boots1: string[];
        boots2: string[];
        bruh: string[];
        candy1: string[];
        candy2: string[];
        candy3: string[];
        candy4: string[];
        candy5: string[];
        candy6: string[];
        candy7: string[];
        deathReaction: {
            f_asriel: string[];
            f_bird: string[];
            f_blooky: string[];
            f_dummy: string[];
            f_hub: string[];
            f_napstablook: string[];
            f_snail: () => string[];
            f_undyne: string[];
            f_village: string[];
        };
        dummy1a: () => string[];
        dummy1b: () => string[];
        dummy1c: () => string[];
        dummy2: () => string[];
        dummy3: string[];
        dummy4: () => string[];
        dummypunch1: string[];
        dummypunch2a: string[];
        dummypunch2b: () => string[];
        dummypunch3: string[];
        epicreaction: () => string[];
        fallenfish: string[];
        fallenfish2: string[];
        finalfish1: string[];
        finalfish2: string[];
        finalpre: string[];
        genotext: {
            asgoreFinal1: () => string[];
            asgoreFinal2: string[];
            asgoreFinal3: string[];
            asgoreMK1: string[];
            asgoreMK2: string[];
            asriel32: string[];
            asriel33: string[];
            asriel34: string[];
            asriel34x: string[];
            asriel35: () => string[];
            asriel36: string[];
            asriel37: () => string[];
            asriel38: () => string[];
            asriel39: string[];
            asriel40: () => string[];
            asriel41: string[];
            asriel42: string[];
            asriel43: () => string[];
            asriel44: string[];
            asriel45: string[];
            asrielHug1: string[];
            asrielHug2: string[];
            asrielHug3: string[];
            bombshell1: string[];
            bombshell2: string[];
            bombshell3: string[];
            bombshell4: string[];
            kidd1: string[];
            kidd2: string[];
            kiddFinal1: () => string[];
            kiddFinal2: string[];
            kiddFinal3: () => string[];
            kiddFinal4: string[];
            kiddFinal5: string[];
            kiddFinal6: string[];
            kiddFinal7: string[];
        };
        goatreaction: () => string[];
        hapstadoor1: string[];
        hapstadoor2: string[];
        jumpsuit1: string[];
        jumpsuit2: string[];
        kiddStatue: string[];
        kitchencall: () => string[];
        madfish1: () => string[];
        madfish2: string[];
        madfish3: () => string[];
        muffet1: () => string[];
        muffet2: () => string[];
        muffetGeno1: () => string[];
        muffetGeno1x: string[];
        muffetGeno2: string[];
        muffetGeno3: string[];
        mushroomdance1: string[];
        mushroomdance2: () => string[];
        musicbox: string[];
        napcomputer1: () => string[];
        napcomputer2: string[];
        napcomputer3: {
            a: (string | (() => "papyrus tribute.kwac" | "funny autotune.kwac"))[];
            b: string[];
        };
        napcomputer4: {
            a: string[];
            b: string[];
        };
        noTem: () => string[];
        noTortoise: string[];
        npc86a: () => string[];
        npc86b: string[];
        npc86c: string[];
        npc86d: () => string[];
        npc86e: () => string[];
        npc86f: () => string[];
        npc86g: () => string[];
        npc86h: () => string[];
        npcinter: {
            f_clamgirl: () => string[];
            f_echo1: () => string[];
            f_echo2: () => string[];
            f_echo3: () => string[];
            f_echo4: () => string[];
            f_echo5: () => string[];
            f_echo6: () => string[];
            f_echo7: () => string[];
            f_echo8: () => string[];
            f_echo9: () => string[];
            f_echoAbyss1: () => string[];
            f_echoAbyss2: () => string[];
            f_echoAbyss3: () => string[];
            f_echoAbyss4: () => string[];
            f_echoAbyss5: () => string[];
            f_echoAbyss6: () => string[];
            f_echoAbyss7: () => string[];
            f_echoAbyss8: () => string[];
            f_echoAbyss9: () => string[];
            f_echoAbyss10: () => string[];
            f_echodude: () => string[];
            f_echoLobby: () => string[];
            f_kidd: () => string[];
            f_longsy: () => string[];
            f_shortsy: () => string[];
            f_snail1: string[];
            f_snail2: string[];
            f_starkiller: () => string[];
            f_temmie1: string[];
            f_temmie2: string[];
            f_temmie3: string[];
            f_temmie4: () => string[];
            f_temmie5: string[];
            f_temmie6: string[];
        };
        plot_call: {
            a: string[];
            a1: string[];
            a2: string[];
            b: () => string[];
        };
        punchcard0: string[];
        punchcard1: string[];
        punchcard2: string[];
        punchcard3: string[];
        punchcard4: string[];
        puzzle1switch: string[];
        puzzle2switch: string[];
        puzzle3switch: string[];
        quiche1: string[];
        quiche2: string[];
        quiche3: string[];
        quiche4: string[];
        quiche5: string[];
        run1: string[];
        run2a: string[];
        run2b: string[];
        run2c: string[];
        run3: string[];
        run4: string[];
        run5: string[];
        run6: string[];
        run6a: string[];
        run6b: string[];
        run6c: string[];
        run6d: string[];
        run7: string[];
        run8: string[];
        run9: string[];
        run10: string[];
        run11: (charged: boolean) => string[];
        sansSentry: () => string[];
        sansSentryBack: () => string[];
        secretcall: string[];
        sleeper: string[];
        sleepersans: string[];
        spider1: () => string[];
        spider2: () => string[];
        spider3: () => string[];
        spider4: () => string[];
        spider5: () => string[];
        spider6: () => string[];
        spookydate0: string[];
        spookydate1: (...args: any[]) => string[];
        spookydate2a: string[];
        spookydate2b: string[];
        spookydate3: string[];
        spookydate4: string[];
        spookydate5: string[];
        spookydate6: string[];
        spookydate7: string[];
        spookydate8: string[];
        spookydate9: string[];
        spookydate9x: string[];
        spookydate9y: string[];
        spookydate9z: string[];
        spookydate10: string[];
        spookydate11: string[];
        spookydate12a: string[];
        spookydate12b: string[];
        spookydate13: string[];
        spookydate14a: () => string[];
        spookydate14b: () => string[];
        spookydate15: string[];
        spookydate16: string[];
        spookydate17: string[];
        spookydate18: string[];
        spookydate19a: string[];
        spookydate19b: string[];
        spookydate20: () => string[];
        spookydate21: () => string[];
        spookydate22: string[];
        spookydate23: () => string[];
        telescopeX: (...args: any[]) => string[];
        telescopeY: string[];
        temmiepat1: string[];
        temmiepat2a: string[];
        temmiepat2b: string[];
        temmiepat3a: string[];
        temmiepat3b: string[];
        temmietourguide: string[];
        temmietourguide1: string[];
        temmietourguide2: string[];
        temstatue: string[];
        temstatueAftuh: string[];
        temstatueNormuh: string[];
        trivia: {
            f_armor_sign: string[];
            f_backsign: string[];
            f_cheesetable: string[];
            f_creamsign: () => string[];
            f_doge_sign: string[];
            f_doge1: string[];
            f_doge3: () => string[];
            f_doge5: () => string[];
            f_gersonshop: string[];
            f_hub_sign: string[];
            f_lobbywindow: string[];
            f_paintblaster: string[];
            f_path1: string[];
            f_path2: string[];
            f_path3: string[];
            f_puzzle1_sign: string[];
            f_puzzle2_sign: string[];
            f_puzzle3_sign: string[];
            f_statue_kidd: string[];
            f_telescope: string[];
            f_temhistory: string[];
            f_temhole: () => string[];
            f_trash: () => string[];
            f_trash1: string[];
            f_trash2: string[];
            f_trash3: string[];
            f_undynedummy: () => string[];
            f_view: string[];
            f_village_egg: string[];
            f_village_sign1: string[];
            f_village_sign2: string[];
            f_village_sign3: string[];
            fstatue: string[];
            hapstabed: string[];
            hapstabook1: string[];
            hapstabook2: string[];
            hapstabook3: string[];
            hapstabook4: string[];
            hapstabook5: string[];
            hapstabook6: string[];
            hapstacouch: string[];
            hapstaposter: string[];
            hapstatv: string[];
            hapstawindow: string[];
            k_bonedrawer: () => string[];
            k_broadsword: () => string[];
            k_closet: () => string[];
            k_fridge: () => string[];
            k_otherdrawer: (...args: any[]) => string[];
            k_piano: (...args: any[]) => string[];
            k_sink: (...args: any[]) => string[];
            k_stove: (...args: any[]) => string[];
            k_window: () => string[];
            plankstop: string[];
            wallsign4: string[];
        };
        truetext: {
            doge1: string[];
            muffet: string[];
            preundyne: string[];
            unddate: () => string[];
            undyne1: () => string[];
            undyne1x: string[];
            undyne2: (...args: any[]) => string[];
            undyne3: string[];
            view1: string[];
            view2: string[];
        };
        unddate0: () => string[];
        unddate0x: () => string[];
        unddate1a: string[];
        unddate1b: (...args: any[]) => string[];
        unddate2a: string[];
        unddate2b: string[];
        unddate3: string[];
        unddate4: string[];
        unddate5: string[];
        unddate5x: string[];
        unddate6: string[];
        unddate7: string[];
        unddate8: string[];
        unddate9: string[];
        unddate10: string[];
        unddate11a: string[];
        unddate11a1a: string[];
        unddate11a1b: string[];
        unddate11a2: string[];
        unddate11b: string[];
        unddate12a: string[];
        unddate12b: string[];
        unddate12c: string[];
        unddate13: string[];
        unddate13a1: string[];
        unddate13a2: string[];
        unddate13a3: string[];
        unddate13a4a: string[];
        unddate13a4b: string[];
        unddate13a5: string[];
        unddate13b: (...args: any[]) => string[];
        unddate13c: (...args: any[]) => string[];
        unddate13d: string[];
        unddate14: string[];
        unddate15a: string[];
        unddate15b: string[];
        unddate15c: string[];
        unddate16: string[];
        unddate17: string[];
        unddate18: string[];
        unddate19x: string;
        unddate19y: string[];
        unddate20: ((...args: any[]) => string[])[];
        unddate21: string[];
        unddate22: string[][];
        unddate22x: string[];
        unddate22y: string[];
        unddate23: string[];
        unddate24: string[][];
        unddate25: string[][];
        unddate25x: string[];
        unddate26: string[];
        unddate27: string[][];
        unddate28: string[];
        unddate29: string[];
        unddate30: string[];
        unddate31: string[];
        unddate32: string[][];
        unddate33: string[];
        unddate34: string[];
        unddate35: string[];
        unddate36: string[];
        unddate37: string[];
        unddate38: string[];
        unddate39a: () => string[];
        unddate39b: () => string[];
        unddate40: (res: number) => string[];
        unddate41: string[];
        unddate41x: string[];
        unddate41y: string[];
        unddate42a: string[];
        unddate42b: string[];
        unddate43: string[];
        unddate44: string[];
        unddate45: string;
        unddate46: string[];
        unddate47: string[];
        unddate48: string[];
        unddate49: string[];
        unddate50: string[];
        unddate51: string[];
        unddate52: string[];
        unddate53: string;
        unddate53x: string[];
        unddate54: string[];
        unddate55: string[];
        unddate56: string[];
        unddate57a: string[];
        unddate57b: string[];
        unddate58: string[];
        unddate59: string[];
        unddate60: string[];
        unddate61: string[];
        unddate62: string[];
        unddate63: string[];
        unddate64: string[];
        unddate65: string[];
        unddate66: string[];
        undyne1a: string[];
        undyne1b: string[];
        undyne1c: () => string[];
        undyne1d: string[];
        undyne1e: string[];
        undyne1f: string[];
        undyne1g: () => string[];
        undyne1h: () => string[];
        undyne1i: string[];
        undyne1j: string[];
        undyne1k: string[];
        undyne1l: string[];
        undyne1m: string[];
        undyne1n: string[];
        undyne1o: string[];
        undyne1p: string[];
        undyne1q: string[];
        undyne1r: string[];
        undyne1s: string[];
        undyne2a: string[];
        undyne2ax: string[];
        undyne2b: string[];
        undyne2bx: string[];
        undyne2c: string[];
        undyne2cx: string[];
        undyne2d: string[];
        undyne2dx: () => string[];
        undyne2ex: string[];
        undynefinal1a: string[];
        undynefinal1b: string[];
        undynefinal1c: string[];
        undynefinal1d: string[];
        undynefinal1e: string[];
        undynefinal1f: string[];
        undynefinal1g: string[];
        undynefinal2a: () => string[];
        undynefinal2b1: string[];
        undynefinal2b1a: string[];
        undynefinal2b1b: string[];
        undynefinal2b2: () => string[];
        undynefinal2b2a: string[];
        undynefinal2b2b: string[];
        undynefinal2b2c: string[];
        undynefinal2b2d: string[];
        undynefinal2b2e: string[];
        undynefinal2b2f: string[];
        undynefinal2b2g: string[];
        undynefinal2b2h: string[];
        undynefinal2b2i: string[];
        undynefinal2b2j: string[];
        undynefinal2b2k: string[];
        undynefinal2b2l: string[];
        undynefinal2b2m: string[];
        undynefinal2b2n: string[];
        undynefinal2b2o: string[];
        undynefinal2b2p: string[];
        undynefinal2b2q: string[];
        undynefinal2b2r: () => string[];
        undynefinal2b2s: string[];
        undynefinal2b2t: string[];
        undynefinal2b3: string[];
        undynefinal2c1: string[];
        undynefinal2c2: string[];
        undynefinal3: () => string[];
        undynefinal3x: string[];
        undynehouse1: string[];
        undynehouse2: string[];
        walktext: {
            bird: () => string[];
            birdx: string[];
            path1: () => string[];
            path2: () => string[];
            path3: () => string[];
            path4: () => string[];
            path5: string[];
            path6: () => string[];
            path7: () => string[];
            path8: () => string[];
            prechase: string[];
            rescue1: string[];
            rescue2: string[];
            rescue3: string[];
            snailcom: string[];
            trashcom: string[];
            undynecom: string[];
        };
        watercooler1: string[];
        watercooler2a: string[];
        watercooler2b: string[];
        watercooler3: string[];
    };
    b_group_moldsmalMoldbygg1: string[];
    b_group_moldsmalMoldbygg2a: () => string[];
    b_group_moldsmalMoldbygg2b: () => string[];
    b_group_moldsmalMoldbygg2c: () => string[];
    b_group_woshuaMoldbygg2: string[];
    b_group_woshuaMoldbygg2a: () => string[];
    b_group_woshuaMoldbygg2b: () => string[];
    b_opponent_woshua: {
        tweet: string;
        act_check: () => string[];
        name: string;
        status1: () => string[];
        idleTalk1a: string[];
        idleTalk1b: string[];
        idleTalk1c: string[];
        idleTalk1d: string[];
        idleTalk1e: string[];
        idleTalk2a: string[];
        idleTalk2b: string[];
        idleTalk2c: string[];
        idleTalk3: () => string[];
        cleanTalk: string[];
        jokeTalk1: string[];
        jokeTalk2: string[];
        randStatus1: () => string[];
        randStatus2: () => string[];
        randStatus3: () => string[];
        randStatus4: () => string[];
        randStatus5: () => string[];
        hurtStatus: () => string[];
        jokeText1: string[];
        jokeText2: string[];
        jokeText3: string[];
        touchText1: string[];
        touchText2: string[];
        cleanText1: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        cleanText2: string[];
    };
    b_opponent_fakemoldsmal: {
        act_check: string[];
        name: string;
        smalTalk: string[];
        fakeStatus1: () => string[];
        fakeStatus2: () => string[];
        fakeStatus3: () => string[];
        fakeStatus4: () => string[];
        act_imitate: string[];
        act_flirt: string[];
        act_slap: string[];
    };
    b_opponent_moldbygg: {
        status1: () => string[];
        act_check: string[];
        name: string;
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        randStatus1: () => string[];
        randStatus2: () => string[];
        randStatus3: () => string[];
        randStatus4: () => string[];
        hurtStatus: () => string[];
        act_handshake: string[];
        act_sit: string[];
        distanceStatus: () => string[];
        act_flirt: string[];
    };
    b_opponent_shyren: {
        act_check: string[];
        awkwardtoot: string[];
        creepStatus: () => string[];
        creepText1: string[];
        creepText2: string[];
        encourage1: () => string[];
        encourage2: () => string[];
        encourage3: () => string[];
        encourage4: () => string[];
        flirtText1: string[];
        flirttoot: string[];
        hum1: string[];
        hum2: string[];
        hum3: string[];
        hum4: string[];
        humX1: () => string[];
        humX2: () => string[];
        humX3: () => string[];
        humX4: () => string[];
        hurtStatus: string[];
        name: string;
        randStatus1: () => string[];
        randStatus2: () => string[];
        randStatus3: () => string[];
        randStatus4: () => string[];
        randStatus5: () => string[];
        sadtalk1: string[];
        sadtalk2: string[];
        smile1: string[];
        smile2: string[];
        smileX: string[];
        status1: () => string[];
        talk3: string[];
        talk4: string[];
        talk5: string[];
        talk6: string[];
        talk7: string[];
        wave1: string[];
        wave2: () => string[];
    };
    b_opponent_radtile: {
        act_check: () => string[];
        name: string;
        status1: () => string[];
        randStatus1: () => string[];
        randStatus2: () => string[];
        randStatus3: () => string[];
        randStatus4: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        insultIdleTalk1: string[];
        insultIdleTalk2: string[];
        insultIdleTalk3: string[];
        act_praise: string[];
        complimentTalk1: string[];
        complimentTalk2: string[];
        complimentTalk3: string[];
        complimentPostInsultTalk1: string[];
        complimentPostInsultTalk2: string[];
        complimentPostInsultTalk3: string[];
        complimentPostInsultStatus: () => string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalk3: string[];
        complimentStatus: () => string[];
        checkTalk: string[];
        realTalk1: string[];
        realTalk2: string[];
        realTalk3: string[];
        realStatus: () => string[];
        realTalkY1: string[];
        realTalkY2: string[];
        realTalkY3: string[];
        shockTalk1: string[];
        shockStatus: () => string[];
        act_insult: string[];
        act_flirt: string[];
        insultTalk1: string[];
        insultTalk2: string[];
        insultTalk3: string[];
        insultStatus: () => string[];
        checkPostInsultTalk: string[];
        checkPostInsultStatus: () => string[];
        hurtStatus: () => string[];
    };
    b_opponent_doge: {
        act_check: () => string[];
        act_flirt: () => string[];
        act_talk: () => string[];
        batheText: string[];
        batheTextEarly: string[];
        batheTextGeno: string[];
        batheTextLate: string[];
        batheTextPost: string[];
        fetchStatus: string[];
        fetchText: () => string[];
        fetchTextEpic: string[];
        fetchTextGarb: string[];
        flirtStatus: () => string[];
        hurtStatus: () => string[];
        name: string;
        petTalkPost: () => string[];
        petText: string[];
        petTextEarly: string[];
        petTextGeno: string[];
        petTextLate: string[];
        petTextPost1: string[];
        petTextPost2: string[];
        petTextPost3: string[];
        petTextPost4: string[];
        petTextPost5: string[];
        petTextPost6: string[];
        petTextPost7: string[];
        petTextSus: string[];
        status1: () => string[];
        talkStatus: () => string[];
        turnStatus1: string[];
        turnStatus2: () => string[];
        turnStatus3: () => string[];
        turnStatus4: () => string[];
        turnStatus5: () => string[];
        turnStatus6: () => string[];
        turnStatus7: () => string[];
        turnStatus8: () => string[];
        turnStatus9: () => string[];
        turnStatus10: () => string[];
        turnTalk1: () => string[];
        turnTalk2: () => string[];
        turnTalk3: () => string[];
        turnTalk4: () => string[];
        turnTalk5: () => string[];
        turnTalk6: () => string[];
        turnTalk7: () => string[];
        turnTalk8: () => string[];
        turnTalk9: () => string[];
        turnTalk10: () => string[];
        turnTalk11: () => string[];
        walkText: string[];
        walkTextEarly: string[];
        walkTextGeno: string[];
        walkTextLate: string[];
        walkTextPost: string[];
        walkTextSus: string[];
    };
    b_opponent_muffet: {
        act_check: string[];
        act_flirt: () => string[];
        act_talk: () => string[];
        appeaseText: string[];
        appeaseTextEarly: string[];
        appeaseTextGeno: string[];
        appeaseTextLate: string[];
        appeaseTextPost: string[];
        appeaseTextSus: string[];
        counterText: string[];
        counterTextEarly: string[];
        counterTextGeno: string[];
        counterTextLate: string[];
        counterTextPost: string[];
        name: string;
        payTalkPost: string[];
        payText: string[];
        payTextEarly: string[];
        payTextGeno: string[];
        payTextLate: string[];
        payTextPost: string[];
        payTextSus: string[];
        status1: string[];
        turnStatus1: () => string[];
        turnStatus2: () => string[];
        turnStatus3: () => string[];
        turnStatus4: () => string[];
        turnStatus5: () => string[];
        turnStatus6: () => string[];
        turnStatus7: () => string[];
        turnStatus8: () => string[];
        turnStatus9: () => string[];
        turnStatus10: () => string[];
        turnStatus11: () => string[];
        turnStatus12: () => string[];
        turnStatus13: () => string[];
        turnTalk1: () => string[];
        turnTalk1a: string[];
        turnTalk2: () => string[];
        turnTalk3: () => string[];
        turnTalk4: () => string[];
        turnTalk5: () => string[];
        turnTalk6: () => string[];
        turnTalk7: () => string[];
        turnTalk8: () => string[];
        turnTalk9: () => string[];
        turnTalk10: () => string[];
        turnTalk11: () => string[];
        turnTalk12: () => string[];
        turnTalk13: () => string[];
    };
    b_opponent_undyne: {
        talkText: string[];
        talkText1: string[];
        talkText2: string[];
        talkText3: string[];
        talkText4: string[];
        talkText5: string[];
        talkText6: string[];
        talkText7: string[];
        talkText8: string[];
        talkText9: string[];
        talkText10: string[];
        talkText11: string[];
        talkText12: string[];
        talkText13: string[];
        talkText14: string[];
        talkText15: string[];
        talkText16: string[];
        talkText17: string[];
        talkText18: string[];
        talkText19: string[];
        talkText20: string[];
        talkText21: string[];
        talkText22: string[];
        spaghetti1: string[];
        spaghetti2: () => string[];
        artifact1: () => string[];
        act_check: () => string[];
        name: () => "* Undyne" | "* Undyne the Undying";
        status1: string[];
        intro1: () => string[];
        intro2: () => string[];
        intro3: string[];
        intro4: string[];
        intro5: string[];
        earlyChallenge: () => string[];
        earlyChallengeStatus: string[];
        randStatus1: string[];
        randStatus2: string[];
        randStatus3: string[];
        randStatus4: string[];
        randStatus5: string[];
        randStatus6: string[];
        randStatus7: string[];
        randStatus8: string[];
        randStatus9: string[];
        randStatus10: string[];
        papStatus1: string[];
        papStatus2: string[];
        papStatus3: string[];
        papStatus4: string[];
        papStatus5: string[];
        endStatus1: string[];
        endStatus2: string[];
        endStatus3: string[];
        endStatus4: string[];
        endStatus5: string[];
        tutorial1: () => string[];
        tutorial2: string[];
        tutorial3: string[];
        tutorial4: string[];
        tutorial5: string[];
        turnTalkA1: () => string[];
        turnTalkA2: () => string[];
        turnTalkA3: () => string[];
        turnTalkA4: () => string[];
        turnTalkA5: () => string[];
        turnTalkA6a: () => string[];
        turnTalkA6b: () => string[];
        turnTalkA7a: () => string[];
        turnTalkA7b: () => string[];
        turnTalkB1: () => string[];
        turnTalkB2: () => string[];
        turnTalkB3: () => string[];
        turnTalkB4: () => string[];
        turnTalkB5: () => string[];
        turnTalkB6: () => string[];
        turnTalkB7a: () => string[];
        turnTalkB7b: () => string[];
        turnTalkB8a: () => string[];
        turnTalkB8b: () => string[];
        turnTalkC1: () => string[];
        turnTalkC2: () => string[];
        turnTalkC3: () => string[];
        turnTalkC4: string[];
        turnTalkC5: string[];
        turnTalkC6: string[];
        turnTalkC7: string[];
        turnTalkC8: string[];
        turnTalkC9a: string[];
        turnTalkC9b: string[];
        turnTalkC10a: string[];
        turnTalkC10b: string[];
        turnTalkD: string[];
        death1: string[];
        death2: string[];
        death3: () => string[];
        death4: string[];
        determination1: string[];
        determination2: string[];
        determination3: string[];
        determination4: string[];
        determination5: string[];
        determination6: string[];
        determination7: string[];
        determination8: string[];
        determination9: string[];
        death5: string[];
        death6: string[];
        death7: string[];
        death8a: string[];
        death8b: string[];
        death8c: string[];
        death9: string[];
        deterStatus1: string[];
        deterStatus2: string[];
        deterStatus3: string[];
        deterStatus4: string[];
        deterStatus5: string[];
        challengeText1: string[];
        challengeText2: string[];
        challengeText3: string[];
        challengeText4: string[];
        challengeText5: string[];
        challengeText6: string[];
        challengeText7: string[];
        pleadText1: string[];
        pleadText2: string[];
        pleadText3: string[];
        pleadText4: string[];
        pleadText5: string[];
        pleadText6: string[];
        genoCutscene1: string[];
        genoCutscene2: string[];
        genoCutscene3: string[];
        genoCutscene3x: string[];
        genoCutscene4: string[];
        genoCutscene5: string[];
        genoCutscene6: string[];
        genoCutscene7: string[];
        genoCutscene8: string[];
        genoCutscene9: string[];
        genoCutscene10: string[];
        genoCutscene11: string[];
        genoCutscene12a: string[];
        genoCutscene12b: string[];
        genoCutscene12c: string[];
        genoCutscene12d: string[];
        genoCutscene12e: string[];
        genoCutscene13: string[];
        genoCutscene14: string[];
        genoCutscene14x: string[];
        genoCutscene15: string[];
        genoCutscene15x: string[];
        genoDeath1: string[];
        genoDeath2: string[];
        genoDeath3: string[];
        genoDeath4: string[];
        lowStatus1: string[];
        lowStatus2: string[];
        lowStatus3: string[];
        lowStatus4: string[];
        lowStatus5: string[];
        genoStatus1: string[];
        genoStatus2: string[];
        genoStatus3: string[];
        genoStatus4: string[];
        genoStatus5: string[];
        trueGenoStatusX: () => string[];
        trueGenoStatus1: string[];
        trueGenoStatus2: string[];
        trueGenoStatus3: string[];
        trueGenoStatus4: string[];
        trueGenoStatus5: string[];
        trueGenoStatus6: string[];
        trueGenoStatus7: string[];
        trueGenoStatus8: string[];
        trueGenoStatusLow1: string[];
        trueGenoStatusLow2: string[];
        asrielExplain: () => string[];
        neutralFinalStatus: string[];
    };
    b_opponent_dateundyne: {
        name: string;
        snacker: string[];
        artichoke: string[];
        intro: string[];
        status1: string[];
        act_check: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        fightTalk: string[];
        flirtTalk0: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalk3: string[];
        flirtStatus0: string[];
        flirtStatus1: string[];
        flirtStatus2: string[];
        flirtText0: string[];
        flirtText1: string[];
        flirtText2: string[];
        flirtText3: string[];
        cutscene1: string[];
        cutscene2a: string[];
        cutscene2b1: string[];
        cutscene2b2: string[];
        cutscene2c: string[];
    };
    i_artifact: {
        battle: {
            description: string;
            name: string;
        };
        drop: () => string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_astrofood: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_sap: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_goggles: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_padd: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_punchcard: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_quiche: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_rations: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_tea: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_tzn: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_flakes: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_temyarmor: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_boots: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_flight_suit: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_snack: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    s_tem: {
        exit: () => string[];
        item: (armorprice: number) => string[];
        itemInfo: () => string[];
        itemPrompt: string;
        itemPurchase: string[];
        itemPurchasePrompt: () => "Buy it for\n$(x)G?" | "Take it?";
        itemSellPrompt: string;
        itemUnavailable: () => "<09>{#p/narrator}* Nothing left." | "<09>{#p/tem}{#k/2}no more item...";
        itemRestricted: string;
        menu: () => string[];
        menuPrompt1: string;
        menuPrompt3: () => "<23>{#p/narrator}* ...but everybody ran." | "<23>{#p/narrator}* ...but nobody came.";
        note: string[];
        sell1: string[];
        sell2: string[];
        talk: string[];
        talkPrompt: string;
        talkText: string[][];
        zeroPrompt: string;
        colleg1: string[];
        colleg2: string[];
        sellExit: string;
        sellValue: string;
        sellStory1: () => string[];
        sellStory2: string[];
        sellStory3: string[];
    };
    s_tortoise: {
        exit: () => string[];
        item: () => string[];
        itemInfo: string[];
        itemPrompt: () => "<09>{#p/monster}{#k/3}Don't expect a discount." | "<09>{#p/monster}{#k/4}What are you lookin' for?";
        itemPurchase: () => string[];
        itemPurchasePrompt: string;
        itemUnavailable: string;
        menu: string[];
        menuPrompt1: string;
        menuPrompt2: string;
        menuPrompt3: () => "<23>{#p/monster}{#k/3}* What are you guys up to now?\n* Wait, don't tell me.\n* None of my business, right?" | "<23>{#p/monster}{#k/2}* Wa ha ha...\n* So you came to see me.\n* What a treat!";
        sell1: () => string[];
        sell2: () => string[];
        talk: () => string[];
        talkPrompt: () => "<09>{#p/monster}{#k/2}Really?\nYOU wanna talk?" | "<09>{#p/monster}{#k/0}Anything you wanna know?";
        talkText: (() => string[])[];
    };
    s_save: {
        f_abyss: {
            name: string;
            text: string[];
        };
        f_battle: {
            name: string;
            text: () => string[];
        };
        f_hub: {
            name: string;
            text: () => string[];
        };
        f_lobby: {
            name: string;
            text: () => string[];
        };
        f_prechase: {
            name: string;
            text: () => string[];
        };
        f_sans: {
            name: string;
            text: () => string[];
        };
        f_shyren: {
            name: string;
            text: () => string[];
        };
        f_tunnel: {
            name: string;
            text: () => string[];
        };
    };
};
export default text;
