import { CosmosKeyed, CosmosProvider } from '../engine/utils';
export declare const edgy: () => boolean;
export declare const solo: () => boolean;
declare const _default: {
    a_starton: {
        gravo: string[];
        cream_get: string[];
        cream_full: string[];
        bunbun: (...args: any[]) => string[];
        emptytable1: string[];
        emptytable2: string[];
        balcony0: string[];
        balcony1: string[];
        balcony2: string[];
        bedbook1: string[];
        bedbook2: string[];
        bedbook3a: string[];
        bedbook3b: string[];
        bedbook4: string[];
        bedbook5: string[];
        bedbook6: string[];
        beddoor1: string[];
        beddoor2: string[];
        candy1: (...args: any[]) => string[];
        candy2: string[];
        candy3: string[];
        candy4: string[];
        candy5: string[];
        capstation1: string[];
        capstation2: string[];
        crossword0: string[];
        crossword1: string[];
        crossword2: string[];
        crossword3a: string[];
        crossword3b: string[];
        crossword4: (...args: any[]) => string[];
        crossword5a: string[];
        crossword5b: string[];
        crossword6: (choice: number) => string[];
        doggo1: () => string[];
        doggo2: string[][];
        doggo3: (...args: any[]) => string[];
        drop_chip: string[];
        drop_cream: string[];
        drop_fail: string[];
        eat_chip: string[];
        eat_cream: string[];
        genotext: {
            asriel1: () => string[];
            asriel2: string[];
            asriel3: () => string[];
            asriel4: string[];
            asriel5: string[];
            asriel6: () => string[];
            asriel7: string[];
            asriel9: string[];
            asriel10: () => string[];
            asriel17: () => string[];
            asriel24: () => string[];
            asriel26: () => string[];
            asriel28: () => string[];
            asriel29: () => string[];
            asriel30: () => string[];
            asriel30a: string[];
            asriel30b: string[];
            asriel30c: string[];
            asriel30d: () => string[];
            papyrusSolo1a: string[];
            papyrusSolo2a: string[];
            papyrusSolo3a: string[];
            papyrusSolo4a: string[];
            papyrusSolo4b: string[];
            papyrusSolo4c: string[];
            papyrusSolo4d: string[];
            papyrusSolo4e: string[];
            papyrusSolo4f: string[];
        };
        gonezo: () => string[];
        doggonopoggo: string[];
        housebloc: string[];
        innkeep1a: (...args: any[]) => string[];
        innkeep1b: () => string[];
        innkeep1c: () => string[];
        innkeep2a: string[];
        innkeep2b: string[];
        innkeep2c: string[];
        innkeep3a: string[];
        innkeep3b: string[];
        innkeep3c: string[];
        innkeep3d: string[];
        innkeep4: string[];
        innkeep5: string[];
        joey1: () => string[];
        kidd1: (...args: any[]) => string[];
        kidd2: () => string[];
        marriage1: string[];
        marriage2: string[];
        marriage3a: string[];
        marriage3b: string[];
        marriage4: string[];
        marriage5: string[];
        maze1: string[];
        maze2a: string[];
        maze2b: string[];
        maze3: string[];
        maze3a: string[];
        maze4: string[];
        maze5: string[];
        maze6: (...args: any[]) => string[];
        maze7: string[][];
        maze8: string[];
        maze9: string[];
        maze10: string[];
        maze11: string[];
        nicecream1: string[];
        nicecream2: string[];
        nicecream3: string[];
        nicecream4: string[];
        nicecream5: string[];
        nicecream6: string[];
        nicecream7: string[];
        nicecream8: string[];
        nicecream9: string[];
        nicecream10: string[];
        nicecreamF1: string[];
        nicecreamF2: string[];
        nicecreamF3: string[];
        nicecreamF4: string[];
        nicecreamF5: string[];
        nicecreamF6: string[];
        nicecreamK1: string[];
        nicecreamK2: string[];
        nicecreamK3: string[];
        nicecreamE: () => string[];
        npcinter: {
            s_genokid: (...args: any[]) => string[];
            g_beautifulfish: () => string[];
            g_bigmouth: () => string[];
            g_bunbun: () => string[];
            g_dogamy: () => string[];
            g_dogaressa: () => string[];
            g_doggo: () => string[];
            g_grillby: () => string[];
            g_punkhamster: () => string[];
            g_redbird: () => string[];
            l_cupjake: () => string[];
            l_kakurolady: string[];
            l_librarian: () => string[];
            l_sweetie: () => string[];
            s_faun: () => string[];
            s_moonrocks1: (...args: any[]) => string[];
            s_moonrocks2: (...args: any[]) => string[];
            t_bunny: () => string[];
            t_icewolf: () => string[];
            t_imafraidjumitebeinagang: () => string[];
            t_kabakk: () => string[];
            t_loverboy: () => string[];
            t_politics: () => string[];
            t_rabbit: () => string[];
            t_smileguy: (...args: any[]) => string[];
            t_wisconsin: () => string[];
            t_zorren: () => string[];
        };
        objinter: {
            ctower0: string[];
            ctower1: string[];
            microwave0: string[];
            microwave1: string[];
            microwave2: string[];
            microwave3: string[];
            microwave4: string[];
            papmail1: string[];
            papmail2: () => string[];
            papmail3: string[];
            puzzle3: string[];
            puzzlechip: string[];
            spagtable0: string[];
            spagtable1: string[];
            spagtable2: string[];
            spagtable2b: string[];
            spagtable3: () => string[];
            xtower1: string[];
        };
        papbooks1: () => string[];
        papbooks2: (...args: any[]) => string[];
        papcomputer1: () => string[];
        papcomputer2: string[];
        papcomputer3: {
            a: string;
            b: string;
            c: string;
            d: string;
            e: string;
        };
        papcomputer4: ((() => {
            a: string;
            b: string;
            c: string;
        }) | {
            a: string;
            b: string;
            c: string;
        })[];
        papcomputer5: string[];
        papcouch0: string[];
        papcouch1: (...args: any[]) => string[];
        papcouch2: string[];
        papcouch3: string[];
        papcouch4: string[];
        papdate0: () => string[];
        papdate1: () => string[];
        papdate2: string[];
        papdate3: (...args: any[]) => string[];
        papdate3a: string[];
        papdate3b: string[];
        papdate4: () => string[];
        papdate4a: string[];
        papdate4b: string[];
        papdate5: () => string[];
        papdate5a: () => string[];
        papdate5b: string[];
        papdate6: () => string[];
        papdate7: () => string[];
        papdate8: () => string[];
        papdate9: () => string[];
        papdate10: () => string[];
        papdate11: string[];
        papdate12: string[];
        papdate13: () => string[];
        papdate13a: () => string[];
        papdate14: string[];
        papdate15a: string[];
        papdate15a1: string[];
        papdate15b: string[];
        papdate16: string[];
        papdate16a: string[];
        papdate17: () => string[];
        papdate17a: () => string[];
        papdate18a: () => string[];
        papdate18b: () => string[];
        papdate19: string[];
        papdate20: () => string[];
        papdate21: string[];
        papdate22: string[];
        papdate23a: string[];
        papdate23b: string[];
        papdate24: string[];
        papdate24a: () => string[];
        papdate25: string[];
        papdate25a: string[];
        papdate25b: string[];
        papdate25c: string[];
        papdate25d: string[];
        papdate25e: string[];
        papdate25f: string[];
        papdate25g: string[];
        papdate25h: () => string[];
        papdate25i: string[];
        papdate25j: () => string[];
        papdate25k: string[];
        papdate26: () => string[];
        papdate27: string[];
        papdate28: string[];
        papdate29: string[];
        papdate30: string[];
        papdate31a: string[];
        papdate31b: string[];
        papdate32: () => string[];
        papdate33: string[];
        papdate33a: () => string[];
        papdate34a: () => string[];
        papdate34b: () => string[];
        papdate35: string[];
        papdate36: string[];
        papdate37: string[];
        papdate38: () => string[];
        papdate39: () => string[];
        papdate39a: () => string[];
        papdate40: () => string[];
        papdate41: {
            a: () => "ROMANCE" | "FRIENDSHIP";
            b: string;
            c: string;
            d: string;
            e: string;
            f: string;
        };
        pappuzzle1: string[];
        pappuzzle2: string[];
        pappuzzle2a: string[];
        pappuzzle2b: string[];
        pappuzzle2c: string[];
        papsink0: string[];
        papsink1: string[];
        papsink2: string[];
        papsink3: string[];
        papsink4: string[];
        papsink5: string[];
        papsink6: string[];
        papsolution0: string[];
        papsolution1: string[];
        papsolution1a: string[];
        papsolution2a: string[];
        papsolution2b: string[];
        papsolution2c: string[];
        papsolution999: string[];
        papsolution999a: string[];
        papspaghet1: string[];
        papspaghet1a: string[];
        papspaghet2a: string[];
        papspaghet2b: string[];
        paptv: () => string[];
        papyrus1: string[];
        papyrus2: string[];
        papyrus3: string[];
        papyrus4: string[];
        papyrus5: string[];
        papyrus6: string[];
        papyrus7: string[];
        papyrus8: string[];
        papyrus9: string[];
        papyrus10: string[];
        papyrus11: string[];
        papyrus12: string[];
        papyrus13: string[];
        papyrus14: string[];
        papyrusFinal1: string[];
        papyrusFinal2: () => string[];
        papyrusFinal3: () => string[];
        papyrusFinal4: () => string[];
        papyrusFinal4a1: string[];
        papyrusFinal4a2: string[];
        papyrusFinal4b1: string[];
        papyrusFinal4b2: string[];
        papyrusFinal4c1: string[];
        papyrusFinal4c2: string[];
        papyrusFinal4d: string[];
        papyrusFinal4e: string[];
        papyrusFinal4f1: string[];
        papyrusFinal4f2: string[];
        papyrusFinal4g: string[];
        papyrusFinal5: string[];
        papyrusFinal6: string[];
        papyrusFinal7: string[];
        papyrusFinal7a: string[];
        papyrusFinal7b: string[];
        papyrusFinal8: string[];
        papyrusFinal8a: string[];
        puzzle3: () => string[];
        robot1: (...args: any[]) => string[];
        robot2: string[];
        robot3: string[];
        robot4: string[];
        robot5: string[];
        robot6: string[];
        robot7: string[];
        robot8: string[];
        robot9: string[];
        robot10: string[];
        robot11: string[];
        robot12: string[];
        robotDead: string[];
        robotTake0: string[];
        robotTake1: string[];
        robotTake2: string[];
        robotTake3: string[];
        robotTake4: string[];
        sans1: string[];
        sans2: string[];
        sans3: string[];
        sans4: string[];
        sans5: string[];
        sans6: string[];
        sans7: string[];
        sans8: string[];
        sans9: string[];
        sans10: string[];
        sansbook1: string[];
        sansbook2: string[];
        sansbook3: string[];
        sansbook4: string[];
        sansbook5: string[];
        sansbook6: string[];
        sansbook7: string[];
        sansbook8: string[];
        sansbook8x: string[];
        sansbook9: string[];
        sansinter: {
            a1: string[];
            a2: string[];
            a3: string[];
            s_papyrus: () => string[];
            s_dogs: () => string[];
            s_jenga: () => string[];
            s_bridge: () => string[];
        };
        sentryPapyrus1: () => string[];
        sentryPapyrus2: (...args: any[]) => string[];
        sentrySans1: () => string[];
        sentrySans2: (...args: any[]) => string[];
        trivia: {
            s_secret_sign: () => string[];
            grillflower: string[];
            librarbywindow1: string[];
            librarbywindow2: string[];
            papwindow: () => string[];
            s_puzzlenote: string[];
            s_backrooms_lessdog: () => string[];
            s_backrooms_lesstable: () => string[];
            s_beddinng_table: string[];
            s_bh_bone: () => string[];
            s_bh_cottonball: string[];
            s_paptrash: () => string[];
            s_bh_fridge: () => string[];
            s_bh_rocktable: () => string[];
            s_bh_sansdoor: string[];
            s_bh_stove: () => string[];
            s_chew: string[];
            s_whew: string[];
            s_crossroads_sign: string[];
            s_doghouse: () => string[];
            s_doghouse_sign: string[];
            s_dogs_sign: string[];
            s_dogstandA: () => string[];
            s_dogstandB: () => string[];
            s_dogstandC: () => string[];
            s_dogtreat: string[];
            s_grillbys_beegstool: string[];
            s_grillbys_drinks: string[];
            s_grillbys_shelf: string[];
            s_grillbys_sidestool: string[];
            s_grillbys_smolstool: () => string[];
            s_helipad: string[];
            s_jenga_sign: string[];
            s_library_window: string[];
            s_librarby_blueBooks: (...args: any[]) => string[];
            s_librarby_desk: string[];
            s_librarby_greenBooks: (...args: any[]) => string[];
            s_librarby_ladder: string[];
            s_librarby_pinkBooks: (...args: any[]) => string[];
            s_librarby_purpleBooks: (...args: any[]) => string[];
            s_librarby_yellowBooks: (...args: any[]) => string[];
            s_math_sign: string[];
            s_pacing_sign: string[];
            s_phonecard: string[];
            s_pr_papbed: () => string[];
            s_pr_papbones: () => string[];
            s_pr_papcloset: () => string[];
            s_pr_papposter: () => string[];
            s_pr_paptable: () => string[];
            s_puzzle1_sign: string[];
            s_puzzle2_sign: string[];
            s_puzzle3_note: string[];
            s_redbook: string[];
            s_sansbox: () => string[];
            s_sheddoor: string[];
            s_slew: string[];
            s_spagnote: string[];
            s_telescope: () => string[];
            s_town_camera1: string[];
            s_trapnote: () => string[];
            s_tree: () => string[];
            doginfo: () => string[];
        };
        truetext: {
            doggo1: string[];
            doggo2: string[];
            dogs1: string[];
            dogs2: string[];
            fetch: () => string[];
            great1: string[];
            great2: string[];
            great3: string[];
            lesser1: string[];
            lesser2: string[];
            papyrus1: string[];
            papyrus3: string[];
            papyrus4: string[];
            papyrus5: string[];
            puzzle1: string[];
            sans1: string[];
            sans3: string[];
            sans4: string[];
            sans5: string[];
            sans6: string[];
            sans7: string[];
            sans8: string[];
            sans9: string[];
            papdate: string[];
        };
        vegetoid: () => string[];
        vegetoidx: () => string[];
        xtowerHiscoreHeader: string;
        xtowerHiscoreNames: {
            kidd: string;
            napstablook: string;
            papyrus: string;
            sans: string;
            undyne: string;
            you: () => "(Unknown)" | "ALPHYS2";
        };
        xtowerMessage1: string;
        xtowerMessage2: string;
        xtowerSans: () => string[];
        xtowerScore: string;
    };
    b_group_dogs: () => string[];
    b_group_spacetopJerry: () => string[];
    b_group_stardrakeSpacetop: () => string[];
    b_group_stardrakeSpacetop2a: () => string[];
    b_group_stardrakeSpacetop2b: () => string[];
    b_group_stardrakeSpacetop2c: () => string[];
    b_group_stardrakeSpacetop2d: () => string[];
    b_group_stardrakeSpacetopJerry: () => string[];
    b_group_stardrakeSpacetopJerry2a: () => string[];
    b_group_stardrakeSpacetopJerry2b: () => string[];
    b_group_stardrakeSpacetopJerry2c: () => string[];
    b_opponent_stardrake: {
        act_check: () => string[];
        act_flirt: () => string[];
        flirtTalk1: string[];
        genoStatus: () => string[];
        heckleStatus: () => string[];
        heckleTalk1: () => string[];
        heckleTalk2: () => string[];
        heckleTalk3: () => string[];
        heckleText1: () => string[];
        heckleText2: () => string[];
        heckleText3: () => string[];
        hurtStatus: () => string[];
        idleTalk1: () => string[];
        idleTalk2: () => string[];
        idleTalk3: () => string[];
        idleTalk4: () => string[];
        idleTalk5: () => string[];
        idleTalk6: () => string[];
        idleTalk7: () => string[];
        jokeStatus: () => string[];
        jokeTalk1: () => string[];
        jokeTalk2: () => string[];
        jokeTalk3: () => string[];
        jokeTalk4: () => string[];
        jokeText1: () => string[];
        jokeText2: () => string[];
        jokeText3: () => string[];
        name: () => "* Chilldrake" | "* Stardrake";
        punTalk1: () => string[];
        punTalk2: () => string[];
        punTalk3: () => string[];
        punText1: string[];
        randStatus1: () => string[];
        randStatus2: () => string[];
        randStatus3: () => string[];
        randStatus4: () => string[];
        randStatus5: () => string[];
        status1: () => string[];
    };
    b_opponent_jerry: {
        act_check: () => string[];
        act_flirt: () => string[];
        ditchText1: string[];
        ditchText1x: () => string[];
        flirtStatus: string[];
        flirtTalk: string[];
        genoStatus: string[];
        hurtStatus: () => string[];
        idleTalk1: () => string[];
        idleTalk2: () => string[];
        idleTalk3: () => string[];
        idleTalk4: () => string[];
        idleTalkSolo1: () => string[];
        idleTalkSolo2: () => string[];
        idleTalkSolo3: () => string[];
        idleTalkSolo4: () => string[];
        name: string;
        randStatus1: () => string[];
        randStatus2: () => string[];
        randStatus3: () => string[];
        randStatus4: () => string[];
        status1: string[];
    };
    b_opponent_mouse: {
        act_check: () => string[];
        act_direct: string[];
        act_disown: string[];
        act_flirt: string[];
        disowned: string[];
        disownStatus: () => string[];
        disownTalk1: string[];
        disownTalk2: string[];
        distrusted: () => string[];
        flirtTalk: string[];
        genoStatus: string[];
        hurtStatus: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        name: string;
        randStatus1: string[];
        randStatus2: string[];
        randStatus3: string[];
        randStatus4: string[];
        remindStatus: () => string[];
        remindTalk1: string[];
        remindTalk2: string[];
        safeStatus: () => string[];
        safeTalk1: string[];
        safeTalk2: string[];
        status1: string[];
    };
    b_opponent_doggo: {
        act_check: () => string[];
        act_flirt: () => string[];
        act_talk: string[];
        fetch: () => string[];
        fetchStatus: () => string[];
        fetchTalk: string[];
        flirt1: string[];
        invisStatus: () => string[];
        name: string;
        normaStatus: () => string[];
        pet: () => string[];
        petStatus: () => string[];
        petTalk1: string[];
        petTalk2: string[];
        petTalk3: string[];
        petTalk4: string[];
        petTalk5: string[];
        petTalk6: string[];
        petTalk7: string[];
        petTalk8: string[];
        petTalk9: string[];
        petTalk10: string[];
        petTalk11: string[];
        petTalk12: string[];
        petTalk13: string[];
        petTalk14: string[];
        query1: string[];
        query2: string[];
        query3: string[];
        status1: () => string[];
        sussy: () => string[];
        talk1: string[];
        talk2: string[];
        talk3: string[];
    };
    b_opponent_lesserdog: {
        act_check: () => string[];
        act_flirt: () => string[];
        act_talk: () => string[];
        fetch: () => string[];
        fetchStatus: () => string[];
        fetchTalk: string[];
        hurtStatus: () => string[];
        name: string;
        petTalk1: string[];
        petTalk2: string[];
        petTalk3: string[];
        petTalk4: string[];
        petTalk5: string[];
        petTalk6: string[];
        petTalk7: string[];
        petTalk8: string[];
        petTalk9: string[];
        petTalk10: string[];
        petTalk11: string[];
        petTalk12: string[];
        petText1: () => string[];
        petText2: () => string[];
        petText3: () => string[];
        petText4: () => string[];
        petText5: () => string[];
        petText6: () => string[];
        petText7: () => string[];
        petText8: () => string[];
        petText9: () => string[];
        petText10: () => string[];
        petText11: () => string[];
        petText12: () => string[];
        petText13: () => string[];
        petText14: () => string[];
        petText15: () => string[];
        petText16: () => string[];
        petText17: () => string[];
        petText18: () => string[];
        petText19: () => string[];
        petText20: () => string[];
        statusX: string[];
        status0: () => string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        status5: () => string[];
        status6: () => string[];
        status7: () => string[];
        status8: () => string[];
        status9: () => string[];
        status10: () => string[];
        status11: () => string[];
        status12: () => string[];
        status13: () => string[];
    };
    b_opponent_dogamy: {
        act_check: () => string[];
        act_talk: string[];
        fetchStatus: () => string[];
        fetchText: () => string[];
        fetchTextLone: () => string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalk3: string[];
        flirtTalk4: string[];
        flirtText: () => string[];
        flirtTextLone: string[];
        loneStatus: () => string[];
        loneTalk1: string[];
        loneTalk2: string[];
        loneTalk3: string[];
        name: string;
        otherPet: string[];
        petNeedStatus: () => string[];
        petStatus: () => string[];
        petTalk1: string[];
        petTalk2: string[];
        petTalk3: string[];
        petTalk4: string[];
        petText: string[];
        petTextLone: () => string[];
        randTalk1: () => string[];
        randTalk2: () => string[];
        randTalk3: () => string[];
        randTalk4: () => string[];
        resmellStatus: () => string[];
        resmellText1: () => string[];
        resmellText2: () => string[];
        resmellText3: () => string[];
        resmellTextLone: () => string[];
        rollStatus: () => string[];
        rollText: () => string[];
        rollTextLone: () => string[];
        smellTalk1: string[];
        smellTalk2: string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        susText: string[];
        fetchTalk: string[];
    };
    b_opponent_dogaressa: {
        act_check: () => string[];
        act_talk: string[];
        fetchTextLone: () => string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalk3: string[];
        flirtTalk4: string[];
        flirtText: () => string[];
        flirtTextLone: string[];
        loneStatus: () => string[];
        loneTalk1: string[];
        loneTalk2: string[];
        name: string;
        otherPet: string[];
        petNeedStatus: () => string[];
        petTalk1: string[];
        petTalk2: string[];
        petTalk3: string[];
        petTalk4: string[];
        petText: string[];
        petTextLone: () => string[];
        randTalk1: () => string[];
        randTalk2: () => string[];
        randTalk3: () => string[];
        randTalk4: () => string[];
        resmellTalkLone: string[];
        resmellTextLone: () => string[];
        rollTextLone: () => string[];
        smellTalk1: string[];
        smellTalk2: string[];
        fetchTalk: string[];
    };
    b_opponent_greatdog: {
        act_check: () => string[];
        act_flirt: () => string[];
        act_talk: string[];
        beckonText: string[];
        closeStatus: () => string[];
        closeText: string[];
        doneText: string[];
        fetch: () => string[];
        fetchStatus: () => string[];
        hurtStatus: () => string[];
        ignoreStatus1: () => string[];
        ignoreStatus2: () => string[];
        name: string;
        petStatus1: () => string[];
        petStatus2: () => string[];
        petStatus3: () => string[];
        petStatus4: () => string[];
        petText0: string[];
        petText1: string[];
        petText2: string[];
        petText3: string[];
        petText4: string[];
        petText5: string[];
        playText1: string[];
        playText2: string[];
        playText3: string[];
        status0: () => string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        waitText: string[];
    };
    b_opponent_papyrus: {
        spanner: string[];
        spannerTalk1: string[];
        spannerTalk2: string[];
        spannerTalk3: string[];
        spannerTalk4: string[];
        sparableSpannerTalk1: string[];
        sparableSpannerTalk2: string[];
        bullySpareTalk: string[];
        act_check: () => string[];
        capture1: string[];
        capture2: string[];
        capture3: string[];
        capture4: string[];
        capture5: string[];
        checkTalk: string[];
        death1: () => string[];
        death2: () => string[];
        dots: string[];
        flirt0: string[];
        flirt1: string[];
        flirt2: string[];
        flirt3a: string[];
        flirt3b: string[];
        flirt4: string[];
        flirt5: string[];
        flirt6: string[];
        flirt7: string[];
        flirtStatus1: string[];
        flirtStatus2: string[];
        flirtStatus3: string[];
        flirtStatus4: string[];
        flirtStatus5: string[];
        flirtStatus6: string[];
        flirtStatus7: string[];
        flirtStatus8: string[];
        flirtStatus9: string[];
        flirtStatus10: string[];
        flirtStatus11: string[];
        hurtStatus: string[];
        insult1: string[];
        insult2: string[];
        insult3: string[];
        insult4: string[];
        name: string;
        randomStatus1: string[];
        randomStatus2: string[];
        randomStatus3: string[];
        randomStatus4: string[];
        randomStatus5: string[];
        randomStatus6: string[];
        randomStatus7: string[];
        randomStatus8: string[];
        randomStatus9: string[];
        spaghetti1: () => string[];
        spaghetti2: string[];
        specialStatus1: string[];
        specialStatus2: string[];
        specialStatus3: string[];
        specialStatus4: string[];
        specialStatus5: string[];
        specialStatus6: string[];
        status1: string[];
        status2: string[];
        talk1: string[];
        talk1x: string[];
        talk2: string[];
        talk3: string[];
        talk4: string[];
        turnTalk0a: string[];
        turnTalk0b: string[];
        turnTalk0c: string[];
        turnTalk0x: string[];
        turnTalk1a: string[];
        turnTalk1b: string[];
        turnTalk2a: string[];
        turnTalk2b: string[];
        turnTalk3: string[];
        turnTalk4: string[];
        turnTalk5: string[];
        turnTalk6: string[];
        turnTalk7: string[];
        turnTalk8: string[];
        turnTalk9: string[];
        turnTalk10: string[];
        turnTalk11a: string[];
        turnTalk11b: string[];
        turnTalk12: string[];
        turnTalk13a: string[];
        turnTalk13b: string[];
        turnTalk14: string[];
        turnTalk15: string[];
        turnTalk16: string[];
        turnTalk17: string[];
        turnTalk18: string[];
        turnTalk19: string[];
        turnTalk19x: string[];
        turnTalk20: string[];
        turnTalk21: string[];
        turnTalk22: string[];
        turnTalk23: string[];
        turnTalk24: string[];
        turnTalk24x: string[];
        turnTalk25: string[];
        secretTalk2: string[];
        secretTalk3: string[];
        secretTalk4: string[];
        secretTalk5: string[];
        secretTalk6: string[];
        secretTalk7: string[];
        secretTalk7x: string[];
        sparableFlirt1: string[];
        sparableFlirt2: string[];
        sparableFlirt3: string[];
        sparableInsult1: string[];
        sparableInsult2: string[];
        sparableInsult3: string[];
    };
    b_opponent_shockpapyrus: {
        act_check: string[];
        idleText1: string[];
        idleText2: string[];
        idleText3: string[];
        name: string;
        sansDeath1: string[];
        sansDeath1a: string[];
        sansDeath2: string[];
        sansDeath3: string[];
        sansDeath4: string[];
        sansDeath4a: string[];
        sansText: string[];
        status1: string[];
        status2: string[];
    };
    b_opponent_shocksans: {
        name: string;
    };
    b_opponent_shockasgore: {
        act_check: string[];
        foodStatus: string[];
        foodText1: string[];
        foodText2: string[];
        idleText: string[];
        introText: string[];
        stickText: string[];
        stickTalk: string[];
        miss: string[];
        name: string;
        status1: string[];
        status2: string[];
        status3: string[];
    };
    i_berry: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_blookpie: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_chip: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_eye: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_fruit: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_glove: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_milkshake: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_nice_cream: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: (...args: any[]) => string[];
    };
    i_pop: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_spaghetti: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_swirl: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_voidy: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    n_shop_blook: {
        exit: () => string[];
        item: () => string[];
        itemInfo: string[];
        itemPrompt: string;
        itemPurchase: string[];
        itemPurchasePrompt: () => "Buy it for\n$(x)G?" | "Take it?";
        itemUnavailable: () => "<09>{#p/narrator}Nothing left." | "<09>{#p/napstablook}{#k/0}oh... i don't have any more...";
        menu: () => string[];
        menuPrompt1: () => string;
        menuPrompt2: string;
        menuPrompt3: () => "<23>{#p/narrator}* ...but everybody ran." | "<23>{#p/narrator}* ...but nobody came.";
        note: () => string[];
        sell1: () => string[];
        sell2: () => string[];
        talk: () => string[];
        talkPrompt: string;
        talkText: (string[] | (() => string[]))[];
        zeroPrompt: string;
    };
    n_shop_hare: {
        exit: () => string[];
        item: () => string[];
        itemInfo: string[];
        itemPrompt: string;
        itemPurchase: string[];
        itemPurchasePrompt: () => "Buy it for\n$(x)G?" | "Take it?";
        itemUnavailable: () => "<09>{#p/narrator}Nothing left." | "<09>{#p/monster}{#k/10}Sorry, I only made one.";
        menu: () => string[];
        menuPrompt1: string;
        menuPrompt2: string;
        menuPrompt3: () => "<23>{#p/narrator}* ...but everybody ran." | "<23>{#p/narrator}* ...but nobody came.";
        note: string[];
        sell1: () => string[];
        sell2: () => string[];
        talk: string[];
        talkPrompt: string;
        talkText: string[][];
        zeroPrompt: string;
    };
    c_name_papyrus: () => "Papyrus's Phone" | "Papyrus and Undyne";
    p_papyrus: Partial<CosmosKeyed<CosmosProvider<string[]>>>;
    s_save: {
        s_crossroads: {
            name: string;
            text: () => string[];
        };
        s_pacing: {
            name: string;
            text: () => string[];
        };
        s_spaghetti: {
            name: string;
            text: () => string[];
        };
        s_town1: {
            name: string;
            text: () => string[];
        };
    };
};
export default _default;
