import { CosmosKeyed, CosmosProvider } from '../engine/utils';
export declare function pms(): string[];
export declare function trueLizard(): 0 | 1 | 2 | 3;
export declare const evac: () => boolean;
declare const text: {
    a_aerialis: {
        puzzlehelp: string[];
        riverboi1: () => string[];
        riverboi2: string[];
        riverboi3: (...args: any[]) => string[];
        papinter1: () => string[];
        papinter2: string[];
        undinter: () => string[];
        corndog1: (...args: any[]) => string[];
        corndog2: string[];
        corndog3: string[];
        corndog2b: string[];
        corndog4: () => string[];
        corndog5: string[];
        corndog6: string[];
        corndog7: string[];
        tvm1: string[];
        tvm2: string[];
        tvm3: string[];
        tvm4: (...args: any[]) => string[];
        tvm5: (...args: any[]) => string[];
        tvm6: () => string[];
        tvm7: string[];
        lockup0: string[];
        lockup1: string[];
        lockup2: string[];
        lockup3: string[];
        lockup4: string[];
        lockup5: string[];
        lockup6: string[];
        gonezo: () => string[];
        spidershop1: string[];
        spidershop2: string[];
        spidershop3: string[];
        spidershop4: string[];
        spidershop5: string[];
        hotelfood0: string[];
        hotelfood1: string[];
        hotelfood2: string[];
        hotelfood3: string[];
        sonic1: string[];
        sonic2: string[];
        tablaphone1: string[];
        tablaphone2: string[];
        moonpie1: () => string[];
        moonpie2: string[];
        ratings: string;
        secretcall: string[];
        story: {
            phonewarn1: () => string[];
            phonegrabber1: () => string[];
            phonegrabber2: string[];
            phonegrabber3: () => string[];
            alphys1: string[];
            alphys2: string[];
            alphys3: () => string[];
            alphys4: string[];
            alphys5: string[];
            alphys6: string[];
            alphys7: string[];
            alphys8: string[];
            alphys9: string[];
            alphys10: string[];
            alphys11: string[];
            alphys11b: string[];
            alphys12: string[];
            alphys13: () => string[];
            alphys14: string[];
            alphys15: () => string[];
            alphys16: string[];
            alphys17: string[];
            rg1a: string[];
            rg1b1: string[];
            rg1b2: string[];
            rg1c: string[];
            rg1d1: string[];
            rg1d2: string[];
            rg1d3: string[];
            rg1e: string[];
            rgcc: string[];
            robocaller1: () => string[];
            robocaller1x: string[];
            robocaller2: string[];
            robocaller2x: string[];
            status: string;
            barricade1: string[];
            barricade1b1: string[];
            barricade1b2: string[];
            barricade1b3: string[];
            barricade1b4: string[];
            barricade2: string[];
            barricade2b1: string[];
            barricade2b2: string[];
            barricade2b3: string[];
            barricade2b4: string[];
            barricade3: string[];
            barricade3b1: string[];
            barricade3b2: string[];
            barricade3b3: string[];
            barricade3b4: string[];
            barricade3c: string[];
            barricadeFail1: string[];
            barricadeFail2: string[];
            barricadeFail2x: string[];
            barricadeFail3: string[];
            barricade4: string[];
            puzzleReaction1: string[];
            cooker1a: string[];
            cooker1b: string[];
            cooker2a1: string[];
            cooker2a2: string[];
            cooker2b: string[];
            cooker3a: string[];
            cooker3b: string[];
            cooker4a: string[];
            cooker4b: string[];
            cooker5: string[];
            cooker6: string[];
            cooker7a: string[];
            cooker7b: string[];
            cooker7c: string[];
            cooker8a1: string[];
            cooker8a2: string[];
            cooker8b: string[];
            cooker9: string[];
            cooker10: string[];
            cooker11: string[];
            cooker12: () => string[];
            cooker12x: string[];
            cooker13: () => string[];
            cooker13x: string[];
            cooker14: string;
            cooker15: string;
            cooker16a: string[];
            cooker16b: string[];
            cooker16c: string[];
            cooker16d: string[];
            cooker16e: string[];
            cooker16f: string[];
            cooker17a: string[];
            cooker17b: string[];
            cooker17c: string[];
            cooker17d: string[];
            cooker17e: string[];
            cooker18a: string[];
            cooker18b: string[];
            cooker18c: string[];
            cooker19a: string[];
            cooker19b: string[];
            cooker19c: string[];
            robocaller3: string[];
            robocaller4: string[];
            robocaller4x: string[];
            cookerX1: string[];
            cookerX2: string[];
            cookerX3: string[];
            cookerX4: string[];
            cookerX5a: string[];
            cookerX5b: string[];
            cookerX6: string[];
            cookerX7: string[];
            cookerX8: string[];
            cookerX9: string[];
            sosorry: string[];
            puzzleReaction2a: string[];
            puzzleReaction2b: string[];
            puzzleReaction2c: string[];
            moneyPre1: () => string[];
            moneyPre2: string[];
            moneyPre3: string[];
            moneyPre4: string[];
            moneyIntro1: string[];
            moneyIntro2: string[];
            moneyIntro3a: string[];
            moneyIntro3b: () => string[];
            moneyIntro4a: string[];
            moneyIntro4b: string[];
            moneyIntro5a: string[];
            moneyIntro6a: string[];
            moneyIntro6b: () => string[];
            moneyIntro7: string[];
            moneyIntro8: string[];
            moneyIntro9: string[];
            moneyIntro10: string[];
            moneyIntro11: string[];
            moneyChat1: () => string[];
            moneyChat1a: () => string[];
            moneyChat1b: () => string[];
            moneyChat1c: () => string[];
            moneyChat2: string[];
            moneyChat2a: () => string[];
            moneyChat2b: () => string[];
            moneyChat2c: string[];
            moneyChat2d: string[];
            moneyChat2e: string[];
            moneyChat3: string[];
            moneyChat3a: string[];
            moneyChat4: () => string[];
            moneyChat4a: () => string[];
            moneyChat4b: () => string[];
            moneyChat4c1: string[];
            moneyChat4c2: () => string[];
            moneyChat5: () => string[];
            moneyTr1: string[];
            moneyTr2: string[];
            moneyTr3: string[];
            moneyHelper: string;
            moneyHelperConfirmed: string;
            moneyItem1: {
                a: string[];
                b: string[];
                c: string[];
                d: string[];
                e: string[];
                f: string[];
                g: string[];
            };
            moneyVote1: string[];
            moneyVote2: () => string[];
            moneyVote2a: () => string[];
            moneyVote3: () => string[];
            moneyVote3x: string[];
            moneyVote4: () => string[];
            moneyVote4a1: () => string[];
            moneyVote4a2: () => string[];
            moneyVote5: () => string[];
            moneyVote5x: string[];
            moneyVote5x1: string[];
            moneyVote5x2a: string[];
            moneyPun1: string[];
            moneyPun1a: string[];
            moneyPun1b: string[];
            moneyVote5x2b: string[];
            moneyVote6: () => string[];
            moneyVote7: string[];
            moneyVote8: string[];
            moneyItem2: {
                a: string[];
                b: string[];
                c: string[];
                d: () => string[];
                e: string[];
                f: () => string[];
                g: () => string[];
            };
            moneyFinal0: () => string[];
            moneyFinal1: () => string[];
            moneyFinal2: string[];
            moneyFinal3: string[];
            moneyFinal4: string[];
            moneyFinal5: string[];
            moneyFinal6: string[];
            moneyItem3: {
                a: string[];
                b: string[];
                c: string[];
                d: string[];
                e: string[];
                f: string[];
                g: string[];
            };
            moneyTrash1: string[];
            moneyTrash2: string[];
            moneyItemPut1: string[];
            moneyItemPut2: string[];
            moneyItemPut3: string[];
            moneyItemPut4: string[];
            moneyOutro1: string[];
            moneyWhisper1: () => string[];
            moneyWhisper2a: string[];
            moneyWhisper2b: string[];
            moneyWhisper3: string[];
            moneyWhisper4: string[];
            napchat0: string[];
            napchat1: string[];
            napchat2a: string[];
            napchat2b: string[];
            truemtt3: string[];
            moneyX1: string[];
            moneyX2a: string[];
            moneyX2b: string[];
            moneyX3: () => string[];
            moneyX4: () => string[];
            moneyX4a: string[];
            moneyX4b: string[];
            moneyX5a: string[];
            moneyX5b: string[];
            moneyX5c: string[];
            moneyX6a: string[];
            moneyX6b: string[];
            moneyX7: string[];
            moneyX8: string[];
            rg2a: string[];
            rg2b: () => string[];
            rg2c1: string[];
            rg2c2: string[];
            rg2c3: string[];
            rg2d: () => string[];
            rg2e: string[];
            hapsta1: string[];
            hapsta2: string[];
            hapsta3a: string[];
            hapsta3b: string[];
            hapsta4: string[];
            hapsta5: string[];
            hapsta6: string[];
            hapsta7: string[];
            hapsta8: string[];
            hapsta9: string[];
            hapsta10: string[];
            hapsta11: string[];
            hapsta12a: () => string[];
            hapsta12b: string[];
            hapsta13: string[];
            hapsta14: string[];
            hapsta15: string[];
            hapsta16: string[];
            hapsta17: string[];
            hapsta18: string[];
            hapsta19: string[];
            hapsta20: string[];
            hapsta21: string[];
            hapsta22: string[];
            hapsta23: string[];
            hapsta24: string[];
            hapsta25: string[];
            hapsta26: string[];
            hapsta27: string[];
            hapsta28: string[];
            hapsta29: string[];
            hapsta30: string[];
            hapsta31: string[];
            hapsta32: () => string[];
            hapsta34: () => string[];
            hapsta35: string[];
            opera1: () => string[];
            opera2: string[];
            opera3: string[];
            opera4: () => string[];
            opera5: string[];
            opera5b: string[];
            opera6: string[];
            opera7: () => string[];
            opera8: string[];
            opera9: string[];
            opera10: string[];
            opera11: string[];
            opera12: string[];
            opera13: string[];
            opera14a: string[];
            opera14b: string[];
            opera14c: string[];
            opera15: string[];
            opera16: string[];
            opera16b: string[];
            opera17: () => string[];
            opera18: () => string[];
            opera19: () => string[];
            opera20: () => string[];
            opera20a: string[];
            opera21: () => string[];
            opera22: () => string[];
            opera23: () => string[];
            opera24: () => string[];
            opera25: () => string[];
            opera25a: string[];
            opera26: () => string[];
            opera27: () => string[];
            opera28: () => string[];
            opera28a: string[];
            opera29: () => string[];
            opera30: () => string[];
            opera31: () => string[];
            opera31a: string[];
            opera32: () => string[];
            opera33: string[];
            opera34: () => string[];
            opera35: () => string[];
            hapsta36: string[];
            hapsta37: string[];
            hapsta38: string[];
            hapsta39: string[];
            hapsta40: string[];
            hapsta41: string[];
            hapsta42: string[];
            hapsta43: string[];
            hapsta44: string[];
            hapsta45: string[];
            hapsta46: string[];
            hapsta47: string[];
            hapsta48: string[];
            hapsta49a: string[];
            hapsta49b: string[];
            hapsta50: string[];
            hapsta51a: string[];
            hapsta51b: string[];
            hapsta52: string[];
            hapsta53: string[];
            hapsta54: string[];
            hapsta55a: string[];
            hapsta55b: string[];
            hapsta56: string[];
            hapsta57a: string[];
            hapsta57b: string[];
            hapsta58: string[];
            hapsta59: string[];
            hapsta60: string[];
            hapsta61: string[];
            hapsta62: string[];
            hapsta63: string[];
            hapsta64: string[];
            hapsta65a: string[];
            hapsta65b: string[];
            hapsta65c: string[];
            hapsta66a: string[];
            hapsta66b: string[];
            hapsta67: string[];
            hapsta68a: string[];
            hapsta68b: string[];
            hapsta68c: string[];
            hapsta69: string[];
            hapsta70: string[];
            hapsta71: string[];
            hapsta72: string[];
            hapsta73: string[];
            hapsta74: string[];
            hapsta75: () => string[];
            hapsta76: string[];
            hapsta77: string[];
            opera36: () => string[];
            opera37: string[];
            opera38: string[];
            operaX1: () => string[];
            operaX2: () => string[];
            operaX3: string[];
            operaX4: () => string[];
            operaX5: () => string[];
            operaX7: string[];
            operaY1: string[];
            operaY2: string[];
            operaY3: string[];
            operaY4: string[];
            end1: () => string[];
            end2: string[];
            end3: () => string[];
            end4: string[];
            end5: () => string[];
            end6: () => string[];
            end7: () => string[];
            end8: string[];
            end9: string[];
            end10: () => string[];
            end11: string[];
            endwalk0: () => string[];
            endwalk1: () => string[];
            endwalk2: () => string[];
            endwalk3: string[];
            endwalk4: () => string[];
            exit: string[];
        };
        overworld: {
            labcamera2: string[];
            labdisplay: string;
            exofountain1: string[];
            exofountain2a: string[];
            exofountain2b: () => string[];
            kneeler: string[];
            kneeler2: string[];
            topdesk1: string[];
            topdesk2: string[];
            topdesk3: string[];
            labstationA: string[];
            labstationB: string[];
            laserbarrrier1: () => string[];
            laserbarrrier2: (...args: any[]) => string[];
            barricade: string[];
            puzzle1done: string[];
            lablizard: {
                a: () => string[];
            };
            mettacrafter1a: string[];
            mettacrafter1b: string[];
            mettacrafter1c: string[];
            mettacrafter2a: string[];
            mettacrafter2b: string[];
            mettacrafter2c: string[];
            platformDeny: () => string[];
            lift: {
                elevatorStory1: () => string[];
                elevatorStory2: () => string[];
                elevatorStory3: string[];
                elevatorStory4: string[];
                elevatorStory6: () => string[];
                elevator1: string[];
                elevator2: string[];
                elevator3: string[];
                elevator4: string[];
                elevator5: string[];
                elevator6: string[];
            };
            terminal1: () => string[];
            terminal2: () => string[];
            terminal3: () => string[];
            terminal4: () => string[];
            terminal5: () => string[];
            recycler: string[];
            recyclerX: string[];
            wallswitch1: string[];
            ingredient1: string[];
            ingredient2: string[];
            ingredient3: string[];
        };
        trivia: {
            powerline: string[];
            a_hotelfood: string[];
            a_virt: string[];
            metposter: string[];
            bedbox: string[];
            a_lab_books1: (...args: any[]) => string[];
            a_lab_books2: (...args: any[]) => string[];
            cream_machine: string[];
            cream_bucket: string[];
            mewposter: string[];
            dogfood: () => string[];
            doublefridge: () => string[];
            virtsign: string[];
            starlingtable: string[];
            starling: string[];
            starling2: string[];
            starling3: string[];
            starling4: string[];
            starling5: string[];
            dttubes: string[];
            papertable: string[];
            vender1: string[];
            vender2: string[];
            toolrack: string[];
            spycamera1: () => string[];
            gameshow_terminal1: () => string[];
            gameshow_terminal2: string[];
            gameshow_terminal3: string[];
            gameshow_terminal4: string[];
            a_path2_sign: () => string[];
            a_path4_sign: string[];
            a_puzzle1_sign: string[];
            labcounter: (mtt: boolean) => string[];
            chesstable: () => string[];
            roomtable: string[];
            flowertable: string[];
            coredoor: string[];
            deadbot: string[];
            corenote1: string[];
            corenote2: string[];
            corenote3: string[];
            corenote4: string[];
            corenote5: string[];
            corenote6: () => string[];
            coresign1: string[];
            coresign2: string[];
            coresign3: string[];
            coresign4: string[];
            coresign5: string[];
            pottedtable: string[];
            potchair: string[];
            cardboard1: string[];
            cardboard2: string[];
            cardboard3: string[];
            labchem: (mtt: boolean) => string[];
            labglobe: (mtt: boolean) => string[];
            labrando: (mtt: boolean) => string[];
            labsink: (mtt: boolean) => string[];
            labscope: (mtt: boolean) => string[];
        };
        puzzle: {
            puzzlestop1a: (...args: any[]) => string[];
            puzzlestop1b: () => string[];
        };
        npc: {
            a_black: (...args: any[]) => string[];
            a_sorry: (...args: any[]) => string[];
            a_thisisnotabomb: (...args: any[]) => string[];
            a_blackfire: (...args: any[]) => string[];
            a_businessdude: () => string[];
            a_greenfire: () => string[];
            a_harpy: () => string[];
            a_madguy: (...args: any[]) => string[];
            a_proskater: () => string[];
            a_clamguy: (...args: any[]) => string[];
            a_pyrope: (...args: any[]) => string[];
            a_vulkin: (...args: any[]) => string[];
            a_heats: (...args: any[]) => string[];
            a_slime_father: (...args: any[]) => string[];
            a_slime_mother: (...args: any[]) => string[];
            a_slime_kid1: (...args: any[]) => string[];
            a_slime_kid2: (...args: any[]) => string[];
            a_diamond1: () => string[];
            a_diamond2: () => string[];
            a_gyftrot: (...args: any[]) => string[];
            a_giftbear: (...args: any[]) => string[];
            a_boomer: (...args: any[]) => string[];
            a_artgirl: (...args: any[]) => string[];
            a_drakemom: () => string[];
            a_drakedad: () => string[];
            a_reg: () => string[];
            a_oni: (...args: any[]) => string[];
            a_charles: (...args: any[]) => string[];
            a_bowtie: (...args: any[]) => string[];
            a_dragon: (...args: any[]) => string[];
            a_foodreceptionist: () => string[];
        };
        genotext: {
            timewaster: () => string[];
            asriel46: string[];
            asriel47: string[];
            asriel48: string[];
            asriel49: string[];
            asriel50: string[];
            asriel51: string[];
            asriel52: () => string[];
            hotel0: () => string[];
            hotel1: () => string[];
            hotelElectrics: string[];
            hotel2: () => string[];
            core0: () => string[];
            core1: string[];
            core2: () => string[];
            core3: () => string[];
            core4a: string[];
            core4b: () => string[];
            core5: string[];
            core6a: () => string[];
            core6b: string[];
            core7a: string[];
            core7b: string[];
            core7c: string[];
            core8a: string[];
            core8aX: () => string[];
            core8b: string[];
            core8c: string[];
            core8d: string[];
            core8e: string[];
            spareketeer: string[];
            azzyBpants: string[];
        };
        coreswitched: string[];
        puzzlesolved: string[];
        nosleep: string[];
        rg1chat: (...args: any[]) => string[];
        rg2chat: (...args: any[]) => string[];
        elevator1: string[];
        elevatorStory1: string[];
        elevator2: string[];
        elevatorStory2: string[];
        elevator3: string[];
        elevator4: string[];
        dinnerdate1: (...args: any[]) => string[];
        dinnerdate2a: (...args: any[]) => string[];
        dinnerdate2b: string[];
        dinnerdate3: string[];
        dinnerdate4: string[];
        dinnerdate5: string[];
        dinnerdate5b: string[];
        dinnerdate6: string[];
        dinnerdate7: string[];
        dinnerdate8: () => string[];
        dinnerdate10: string[];
        dinnerdate11: () => string[];
        dinnerdate13: string[];
        dinnerdate14: string[];
        dinnerdate14comment: () => string[];
        dinnerdate15: () => string[];
        dinnerdate16: () => string[];
        dinnerdate18: string[];
        dinnerdate19: () => string[];
        onionsan1: string[];
        onionsan1a: string[];
        onionsan2: () => string[];
        onionsan2a: () => string[];
        onionsan3: string[];
        onionsan3a: () => string[];
        onionsan4: string[];
        onionsan4a: string[];
        onionsan4x: string[];
        candy1: (...args: any[]) => string[];
        candy2: string[];
        candy3: string[];
        candy4: string[];
        candy5: string[];
        bedreceptionist1: (...args: any[]) => string[];
        bedreceptionist2a: string[];
        bedreceptionist2b: string[];
        bedreceptionist3: string[];
        bedreceptionist4: string[];
        core1: string[];
        core2a: () => string[];
        core2b: () => string[];
        core3: string[];
        core4: () => string[];
        core5: string[];
        core6: () => string[];
        core7: string[];
        core8a: string[];
        core8a1: string[];
        core8b: string[];
        core8b1: string[];
        core8c: string[];
        core8c1: string[];
        core8c2: string[];
        core8c3: string[];
        core8c4: string[];
        core9a: () => string[];
        core9a1: string[];
        core9b: () => string[];
        core9b1: () => string[];
        core9c: () => string[];
        core10a: string[];
        core10b: string[];
        core10c: string[];
        core11: string[];
        core12: string[];
        core13: string[];
        core14: string[];
        core15: string[];
    };
    b_group_froggitexWhimsalot: () => string[];
    b_group_froggitexWhimsalotX: (froggitex: boolean) => string[];
    b_group_astigmatism: () => string[];
    b_group_rg: () => string[];
    b_group_spacetopTsundere: () => string[];
    b_group_spacetopTsundereX: (spacetop: boolean) => string[];
    b_group_pyropeTsundere: () => string[];
    b_group_pyropeTsundereX: (pyrope: boolean) => string[];
    b_group_astigmatismMigospelX: string[];
    b_opponent_glyde: {
        name: string;
        act_check: string[];
        act_secret: () => string[];
        act_flirt1: string[];
        act_flirt2: string[];
        act_flirt3: string[];
        fightEnder1: string[];
        fightEnder2: string[];
        fightEnder3: string[];
        fightItem1: string[];
        fightItem2: string[];
        intro1: string[];
        intro2a: () => string[];
        intro2b: string[];
        intro2c: string[];
        intro3: string[];
        status1: string[];
        turn1a: string[];
        turn1b: string[];
        turn1c: string[];
        turn1d: string[];
        turn1e: string[];
        turnStatus1: string[];
        turn2: string[];
        turnStatus2: string[];
        turn3: string[];
        turnStatus3: string[];
        turn4: string[];
        turnStatus4: string[];
        turn5: string[];
        turn5a: string[];
        turn5b: string[];
        turn5c: string[];
        turnStatus5: string[];
        turn6a: string[];
        turn6b: string[];
        turn6c: () => string[];
        turn6d: string[];
        turn6e: string[];
        turn6f: string[];
        turn6g: string[];
        turn6h: string[];
        hurtStatus: string[];
    };
    b_opponent_mettaton1: {
        name: string;
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        old_gun_talk: string[];
        old_bomb_talk: string[];
        old_spray_talk: string[];
        status1: () => string[];
        act_check: string[];
        act_flirt: string[];
        yellow1: string[];
        yellow2: string[];
        checkTalk: string[];
        attackTalk: () => string[];
        flirtTalk: string[];
        turn1: string[];
        turn1a1: string[];
        turn1a2: string[];
        turn1b1: () => string[];
        turn1b2: () => string[];
        turn1c: string[];
        turn1d: () => string[];
        turn1e: string[];
        turn1f: string[];
        turn1g: string[];
        turn2: string[];
        turn3: string[];
        turn4a1: string[];
        turn4a2: string[];
        turn4e: string[];
        turn4f: string[];
        turn4g: string[];
        turn4h: string[];
        turn4i: string[];
        turn4j: string[];
        turn5a1: string[];
        turn5a2: () => string[];
        turn5end1: () => string[];
        turn5end2: string[];
        turn6: string[];
        turn7a: string[];
        turn7b1: string[];
        turn7b2: string[];
        turn7b3: string[];
        turn7c: string[];
        turn7d1: string[];
        turn7d2: string[];
        turn7e: string[];
        turn7f: string[];
        turn7g1: string[];
        turn7g2: string[];
        turn7h: string[];
        turn7i: string[];
        turn7j1: string[];
        turn7j2: string[];
        turn7k: string[];
        turn7l1: string[];
        turn7l2: string[];
        turn7l3: string[];
        turn7m: string[];
        turn7n: string[];
        turn7o1: string[];
        turn7o2: string[];
        turn8a1: string[];
        turn8a2: string[];
        turn8end1a: string[];
        turn8end1b: string[];
        turn8end3a: string[];
        turn8end3b: string[];
        turn8end4: string[];
        turn8end5: string[];
        turn8end6: string[];
        turn9a: string[];
        turn9b: () => string[];
        turn9c: string[];
        turn9d: string[];
        turn9e: () => string[];
        turn9end1: string[];
        turn9end2: () => string[];
        turn9end3: string[];
        turn9end4: string[];
        turn9end5: string[];
        turn9end6: string[];
        turn9end7: string[];
        turn1status: string[];
        turn2status: string[];
        turn3status: string[];
        turn4status: string[];
        turn4statusX: string[];
        turn5status: string[];
        turn6status: string[];
        turn7status: string[];
        turn7statusX: string[];
        turn8status: string[];
        turn2react1: string[];
        turn3react1: string[];
        turn4react1: string[];
        turn5react1: string[];
        turn6react1: string[];
        turn7react1: string[];
        turn8react1: string[];
        turn8reactMD1a: string[];
        turn8reactMD2a: string[];
        turn2react2: string[];
        turn3react2: string[];
        turn4react2: string[];
        turn5react2: string[];
        turn6react2: string[];
        turn7react2: string[];
        turn8react2: string[];
        turn8reactMD1b: string[];
        turn8reactMD2b: string[];
        missIndicator: string;
        idleTalk1: () => string[];
        idleTalk2: () => string[];
        idleTalk3: string[];
        idleTalk4: () => string[];
        idleTalk5: string[];
        idleTalk6: string[];
        flirtTalk1: () => string[];
        flirtTalk2: () => string[];
        flirtTalk3: () => string[];
        flirtTalk4: string[];
        flirtTalk5: string[];
        act_turn: string[];
        turnTalk1: string[];
        turnTalk2: string[];
        turnTalk3: string[];
        turnTalk4: () => string[];
        turnTalk5: string[];
        act_burn: string[];
        burnTalk1: string[];
        burnTalk2: string[];
        burnTalk3: string[];
        burnTalk4: string[];
        burnTalk5: string[];
    };
    b_opponent_mettaton2: {
        hint: string[];
        name: () => "* Mettaton NEO" | "* Mettaton EX";
        spannerReaction: (repeat: boolean) => string[];
        artifactReaction: (repeat: boolean) => string[];
        old_gun_text: () => string[];
        old_bomb_text: () => string[];
        old_spray_text: () => string[];
        act_check: () => string[];
        tvmReaction: {
            radio: string[];
            fireworks: string[];
            mewmew: string[];
        };
        act_boast: string[];
        act_heel: string[];
        act_pose1: string[];
        act_pose2: string[];
        act_pose3: string[];
        act_pose4: string[];
        act_scream: string[];
        act_flirt1: string[];
        act_flirt2: string[];
        act_flirt3: string[];
        act_flirt4: string[];
        status1: () => string[];
        statusX: () => string[];
        turnTalk1: () => string[];
        turnTalk2: () => string[];
        turnTalk3: () => string[];
        turnTalk4: () => string[];
        turnTalk5: () => string[];
        turnTalk6: () => string[];
        turnTalk7: () => string[];
        turnTalk8: () => string[];
        turnTalk9: () => string[];
        turnTalk10: () => string[];
        turnTalk11: () => string[];
        turnTalk12: () => string[];
        turnTalk13: () => string[];
        turnTalk14: () => string[];
        turnTalk15: () => string[];
        turnTalk16: () => string[];
        turnTalk17: () => string[];
        turnTalk18: () => string[];
        turnTalk19: () => string[];
        turnTalk20: () => string[];
        turnTalk21: (r: boolean) => string[];
        audienceRec1: () => string[];
        audienceRec2: string[];
        audienceRec3a: string[];
        audienceRec3b: string[];
        audienceRec3c: string[];
        audienceRec4: () => string[];
        neointro: string[];
        mettahero1: string[];
        mettahero2: string[];
        napstahero1: string[];
        napstahero2: string[];
        napstahero3: () => string[];
        qq: () => "Would you forgive a ghost?" | "Would you smooch a ghost?" | "Would you attack a ghost?";
        qa: () => string[];
        q0: () => string[];
        q1: () => string[];
        q2: () => string[];
        q3: () => string[];
        q4: () => string[];
        hitIndicator: string;
        shieldIndicator: string;
        ratings: {
            pose1: string;
            pose2: string;
            pose3: string;
            pose4: string;
            flirt1: string;
            flirt2: string;
            flirt3: string;
            flirt4: string;
            boast1: string;
            boast2: string;
            boast3: string;
            heel1: string;
            heel2: string;
            heel3: string;
            hurt: string;
            bomb: string;
            scream: string;
            hopbox: string;
            hearthurt: string;
            item: {
                old_gun: string;
                old_bomb: string;
                old_spray: string;
                tvm_radio: string;
                tvm_fireworks: string;
                tvm_mewmew: string;
                spanner: string;
                armor: string;
                weapon: string;
                artifact1: string;
                artifact2: string;
                repeat: string;
                pain: string;
            };
            smooch: string;
            nosmooch: string;
        };
    };
    b_opponent_madjick: {
        name: string;
        hint: string[];
        assistTalk1: string[];
        assistAction: string[];
        assistTalk2: string[];
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        status1: () => string[];
        act_check: () => string[];
        idleStatus1: () => string[];
        idleStatus2: () => string[];
        idleStatus3: () => string[];
        idleStatus4: () => string[];
        idleStatus5: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        danceText1: string[];
        danceTalk1: string[];
        danceStatus1: () => string[];
        danceText2: () => string[];
        danceTalk2: string[];
        danceStatus2: () => string[];
        danceText3: string[];
        danceIdleTalk1: string[];
        danceIdleTalk2: string[];
        danceIdleTalk3: string[];
        danceStatus3: () => string[];
        playdeadText1: () => string[];
        playdeadTalk: string[];
        playdeadStatus: () => string[];
        playdeadIdleTalk1: string[];
        playdeadIdleTalk2: string[];
        playdeadIdleTalk3: string[];
        playdeadText2: string[];
        flirtText0: () => string[];
        flirtText1: () => string[];
        flirtTalk1: string[];
        flirtStatus1: () => string[];
        flirtText2: () => string[];
        flirtTalk2: string[];
        flirtStatus2: () => string[];
        flirtText3: () => string[];
        flirtIdleTalk1: string[];
        flirtIdleTalk2: string[];
        flirtIdleTalk3: string[];
        perilStatus: () => string[];
    };
    b_opponent_knightknight: {
        name: string;
        hint: string[];
        assistTalk1: string[];
        assistAction: string[];
        assistTalk2: string[];
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        status1: () => string[];
        act_check: () => string[];
        idleStatus1: () => string[];
        idleStatus2: () => string[];
        idleStatus3: () => string[];
        idleStatus4: () => string[];
        idleStatus5: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        comfortText1: () => string[];
        comfortTalk1: string[];
        comfortStatus1: () => string[];
        comfortText2: () => string[];
        comfortTalk2: string[];
        comfortStatus2: () => string[];
        comfortTalk3: string[];
        comfortStatus3: () => string[];
        comfortText3: string[];
        comfortText4: string[];
        comfortIdleTalk1: string[];
        comfortIdleTalk2: string[];
        comfortIdleTalk3: string[];
        comfortStatus4: () => string[];
        flashText1: () => string[];
        flashTalk: string[];
        flashStatus: () => string[];
        flashIdleTalk1: string[];
        flashIdleTalk2: string[];
        flashIdleTalk3: string[];
        flashText2a: string[];
        flashText2b: string[];
        flashText2c: string[];
        flirtText0: () => string[];
        flirtText1: () => string[];
        flirtTalk1: string[];
        flirtStatus1: () => string[];
        flirtText2: () => string[];
        flirtTalk2: string[];
        flirtStatus2: () => string[];
        flirtText3: () => string[];
        flirtIdleTalk1: string[];
        flirtIdleTalk2: string[];
        flirtIdleTalk3: string[];
        perilStatus: () => string[];
    };
    b_opponent_froggitex: {
        name: string;
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        act_check: () => string[];
        idleText1: string[];
        idleText2: string[];
        idleText3: string[];
        idleText4: string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        act_flirt: () => string[];
        flirtText: () => string[];
        act_translate1: () => string[];
        act_translate2: string[];
        translateText1: () => string[];
        translateText2: () => string[];
        translateText3: () => string[];
        translateText4: () => string[];
        translateText5: () => string[];
        mercyStatus: () => string[];
        act_mystify: string[];
        perilStatus: () => string[];
    };
    b_opponent_whimsalot: {
        name: string;
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        act_check: () => string[];
        act_perch1: () => string[];
        act_perch2: () => string[];
        act_perch3: () => string[];
        act_flirt: () => string[];
        flirtTalk: () => string[];
        act_poke1: () => string[];
        act_poke2: () => string[];
        preperchText1: string[];
        preperchText2: string[];
        preperchText3: string[];
        perchText1: string[];
        perchText2: string[];
        perchText3: string[];
        perchText4: string[];
        perchText5: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        perilStatus: () => string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        status5: () => string[];
        spareStatus: () => string[];
    };
    b_opponent_astigmatism: {
        name: string;
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        act_check: () => string[];
        act_stare: string[];
        act_smile: string[];
        act_flirt: () => string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        status5: () => string[];
        perilStatus: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        flirtTalk: string[];
        partialTalk1: string[];
        partialTalk2: string[];
        partialTalk3: string[];
        partialStatus1: () => string[];
        partialStatus2: () => string[];
        partialStatus3: () => string[];
        fullStatus: () => string[];
        partialIdleTalk1: string[];
        partialIdleTalk2: string[];
        partialIdleTalk3: string[];
        fullIdleTalk1: string[];
        fullIdleTalk2: string[];
        fullIdleTalk3: string[];
        flirtTalkFull: string[];
        hurtTalk: string[];
    };
    b_opponent_migospel: {
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        act_check: () => string[];
        act_flirt: () => string[];
        act_talk: string[];
        flirtTalk: string[];
        groupInsult: string[];
        groupStatus1: () => string[];
        groupStatus2: () => string[];
        groupTalk1: string[];
        groupTalk2: string[];
        groupTalk3: string[];
        groupTalk4: string[];
        groupTalk5: string[];
        groupTalk6: string[];
        name: string;
        soloInsult: string[];
        soloStatus: () => string[];
        soloTalk1: string[];
        soloTalk2: string[];
        soloTalk3: string[];
        soloTalk4: string[];
        soloTalk5: string[];
        talkTalk: string[];
        perilTalk: string[];
    };
    b_opponent_mushketeer: {
        name: string;
        old_gun_text: string[];
        old_bomb_text: string[];
        old_spray_text: string[];
        idleTalk1: () => string[];
        idleTalk2: () => string[];
        idleTalk3: () => string[];
        hurtStatus: () => string[];
        genoStatus: string[];
        status0: () => string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        status5: () => string[];
        travelStatus1: () => string[];
        travelStatus2: () => string[];
        travelStatus3: () => string[];
        act_check: () => string[];
        act_flirt: () => string[];
        flirtTalk: string[];
        flirtStatus: () => string[];
        act_travel1: () => string[];
        act_travel2: () => string[];
        act_travel3: () => string[];
        travelTalk1: string[];
        travelTalk2: string[];
        act_disarm1: () => string[];
        act_disarm2: () => string[];
        act_disarm3: () => string[];
        disarmTalk: string[];
    };
    b_opponent_pyrope: {
        name: string;
        genoStatus: string[];
        genoSpareStatus: string[];
        act_check: () => string[];
        act_flirt: string[];
        sparkText1: string[];
        sparkText2: string[];
        sparkText3: string[];
        rapText1: string[];
        rapText2: string[];
        rapText3: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        flirtTalk: string[];
        sparkTalk1A: string[];
        sparkTalk2A: string[];
        sparkTalk3A: string[];
        sparkFlirtTalkA: string[];
        sparkTalk1B: string[];
        sparkTalk2B: string[];
        sparkTalk3B: string[];
        sparkFlirtTalkB: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        status5: string[];
        sparkStatus1A: string[];
        sparkStatus2A: string[];
        sparkStatus3A: string[];
        sparkStatus1B: string[];
        sparkStatus2B: string[];
        sparkStatus3B: string[];
        hurtStatus: () => string[];
    };
    b_opponent_perigee: {
        name: string;
        genoStatus: string[];
        act_check: () => string[];
        act_flirt: () => string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        flirtTalk: string[];
        whistleTalk: string[];
        whistleStatus: string[];
        act_bow1: string[];
        act_bow2: string[];
        act_whistle: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        status5: string[];
        status6: () => string[];
        hurtStatus: () => string[];
    };
    b_opponent_tsundere: {
        name: string;
        act_check: () => string[];
        flirtText1: string[];
        flirtText2: string[];
        flirtText3: string[];
        flirtText4: string[];
        flirtText5: string[];
        stealText: string[];
        upgradeText1: string[];
        upgradeText2: string[];
        upgradeText3: string[];
        upgradeText4: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalk3: string[];
        flirtTalk4: string[];
        upgradeTalk1: string[];
        upgradeTalk2: string[];
        upgradeTalk3: string[];
        stealTalk1: string[];
        stealTalk2: string[];
        stealTalk3: string[];
        upgradeStatus1: () => string[];
        upgradeStatus2: () => string[];
        upgradeStatus3: () => string[];
        status1: () => string[];
        status2: () => string[];
        status3: () => string[];
        status4: () => string[];
        status5: () => string[];
        status6: () => string[];
        hurtStatus: () => string[];
    };
    b_opponent_rg03: {
        name: string;
        act_check: () => string[];
        randTalk1: () => string[];
        randTalk2: () => string[];
        randTalk3: () => string[];
        randTalk4: () => string[];
        randStatus1: string[];
        randStatus2: string[];
        randStatus3: string[];
        randStatus4: string[];
        randStatus5: string[];
        randTalkLone1: () => string[];
        randTalkLone2: () => string[];
        randTalkLone3: () => string[];
        randTalkLone4: () => string[];
        randStatusLone: () => string[];
        act_flirt: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalkNervy1: string[];
        flirtTalkNervy2: string[];
        flirtTalkLone: string[];
        flirtStatus: string[];
        flirtStatusNervy: string[];
        flirtStatusLone: string[];
        act_flirt_happy: string[];
        act_tug: string[];
        tugTalk1: string[];
        tugTalk2: string[];
        tugTalk3: string[];
        tugTalk4: string[];
        tugStatus: string[];
        act_tug_lone: string[];
        tugTalkLone: string[];
        tugStatusLone: string[];
        act_tug_happy: string[];
        tugShock: string[];
        nervyTalk1: string[];
        nervyTalk2: string[];
        nervyTalk3: string[];
        nervyTalk4: string[];
        nervyStatus: string[];
        act_whisper: string[];
        act_whisper_alt: string[];
        confess1: string[];
        confess2: string[];
        confess3: string[];
        confess4: string[];
        confess5a: string[];
        confess5b: string[];
        confess5c: string[];
        confess6: string[];
        confess7: string[];
        confess8: string[];
        confess9: string[];
        confess10: string[];
        confess11: string[];
        happyTalk1: string[];
        happyTalk2: string[];
        happyTalk3: string[];
        happyTalk4: string[];
        happyStatus: string[];
        horrorTalk1: string[];
        horrorTalk2: string[];
        horrorTalk3: string[];
        horrorTalk4: string[];
        horrorStatus: string[];
        dangerStatus: () => string[];
    };
    b_opponent_rg04: {
        name: string;
        act_check: () => string[];
        randTalk1: string[];
        randTalk2: () => string[];
        randTalk3: () => string[];
        randTalk4: string[];
        randTalkLone1: () => string[];
        randTalkLone2: () => string[];
        randTalkLone3: () => string[];
        randTalkLone4: () => string[];
        randStatusLone: () => string[];
        act_flirt: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalkNervy1: string[];
        flirtTalkNervy2: string[];
        flirtTalkLone: string[];
        flirtStatusLone: string[];
        act_flirt_happy: string[];
        act_tug: string[];
        act_tug_geno: string[];
        tugTalk1: string[];
        tugTalk2: string[];
        tugTalk3: string[];
        tugTalk4: string[];
        tugStatus: string[];
        tugGenoStatus: string[];
        act_tug_lone: string[];
        tugTalkLone: string[];
        tugStatusLone: string[];
        act_tug_hold: string[];
        holdTalk: string[];
        holdStatus: string[];
        act_tug_hold_lone: string[];
        holdTalkLone: string[];
        holdStatusLone: string[];
        act_tug_happy: string[];
        tugSuccessStatus: string[];
        tugShock: string[];
        nervyTalk1: string[];
        nervyTalk2: string[];
        nervyTalk3: string[];
        nervyTalk4: string[];
        act_whisper: string[];
        act_whisper_alt: string[];
        happyTalk1: string[];
        happyTalk2: string[];
        happyTalk3: string[];
        happyTalk4: string[];
        horrorTalk1: string[];
        horrorTalk2: string[];
        horrorTalk3: string[];
        horrorTalk4: string[];
        dangerStatus: () => string[];
    };
    c_name_alphys: string;
    c_name_puzzle: string;
    c_name_dimboxA: string;
    c_name_dimboxB: string;
    c_name_pms: () => "§fill:#ff0§OuterNet (NEW)" | "OuterNet";
    c_puzzle2a: (...args: any[]) => string[];
    c_puzzle2b: (...args: any[]) => string[];
    i_tvm_radio: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_tvm_fireworks: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_tvm_mewmew: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_starfait: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_legendary_hero: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_glamburger: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_face_steak: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_starfait_x: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_legendary_hero_x: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_glamburger_x: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_face_steak_x: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_trash: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_laser: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_visor: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_filament: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_filament_use1: {
        battle: {
            description: string;
            name: string;
        };
        info: string[];
        name: string;
    };
    i_filament_use2: {
        battle: {
            description: string;
            name: string;
        };
        info: string[];
        name: string;
    };
    i_filament_use3: {
        battle: {
            description: string;
            name: string;
        };
        info: string[];
        name: string;
    };
    i_filament_use4: {
        battle: {
            description: string;
            name: string;
        };
        info: string[];
        name: string;
    };
    i_tablaphone: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_sonic: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_mystery_food: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_super_pop: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_old_gun: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_old_bomb: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_old_spray: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_corndog: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_corngoat: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_moon_pie: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    n_sidebarCellPms1: () => "POSTS" | "PRIVATE MESSAGES";
    n_sidebarCellPms2: string;
    n_sidebarCellPms3: {
        alphysBadLizard: {
            author: string;
            pm: string;
        };
        alphys0: {
            author: string;
            pm: string;
        };
        alphys1: {
            author: string;
            pm: () => string;
        };
        alphys2: {
            author: string;
            pm: () => string;
        };
        alphys3: {
            author: string;
            pm: () => string;
        };
        alphys4: {
            author: string;
            pm: () => string;
        };
        alphys6: {
            author: string;
            pm: string;
        };
        alphys7: {
            author: string;
            pm: () => string;
        };
        alphys8: {
            author: string;
            pm: string;
        };
        alphys9: {
            author: () => string;
            pm: () => string;
        };
        alphys10: {
            author: string;
            pm: () => string;
        };
        alphys11: {
            author: string;
            pm: () => "Wouldn't you like to know!\nFUHUHU!" | "ARE WE WATCHING \"TV SHOWS\" NOW?\nSOUNDS EXCITING!" | "Sorry Alphys, I'd love to talk about Mew Mew, just not right now okay?";
        };
        alphys12: {
            author: string;
            pm: string;
        };
        alphys13: {
            author: string;
            pm: () => string;
        };
        alphys14: {
            author: string;
            pm: () => string;
        };
        alphys15: {
            author: string;
            pm: () => string;
        };
        alphys16: {
            author: string;
            pm: string;
        };
        alphys17: {
            author: string;
            pm: string;
        };
        alphys18: {
            author: string;
            pm: string;
        };
        napsta: {
            author: string;
            pm: string;
        };
        alphysX0: {
            author: string;
            pm: string;
        };
        alphysX1: {
            author: string;
            pm: string;
        };
        alphysX2: {
            author: string;
            pm: string;
        };
        alphysX3: {
            author: string;
            pm: string;
        };
        alphysX4: {
            author: string;
            pm: string;
        };
        alphysX5: {
            author: string;
            pm: string;
        };
        alphysX6: {
            author: string;
            pm: string;
        };
        alphysX7: {
            author: string;
            pm: string;
        };
        alphysX8: {
            author: string;
            pm: string;
        };
        alphysX9: {
            author: string;
            pm: string;
        };
        alphysY1: {
            author: string;
            pm: string;
        };
        alphysY2: {
            author: string;
            pm: string;
        };
        alphysY3: {
            author: string;
            pm: string;
        };
        alphysY4: {
            author: string;
            pm: string;
        };
        alphysY5: {
            author: string;
            pm: string;
        };
        alphysY6: {
            author: string;
            pm: string;
        };
        alphysY7: {
            author: string;
            pm: string;
        };
        alphysY8A1: {
            author: string;
            pm: string;
        };
        alphysY8A1a: {
            author: string;
            pm: string;
        };
        alphysY8A1b: {
            author: string;
            pm: string;
        };
        alphysY8A1c: {
            author: string;
            pm: string;
        };
        alphysY8A2: {
            author: string;
            pm: string;
        };
        alphysY8A3: {
            author: string;
            pm: string;
        };
        alphysY8A4: {
            author: string;
            pm: string;
        };
        alphysY8A5: {
            author: string;
            pm: string;
        };
        alphysY8A6: {
            author: string;
            pm: string;
        };
        alphysY8A7: {
            author: string;
            pm: string;
        };
        alphysY8A8: {
            author: string;
            pm: string;
        };
        alphysY8B1: {
            author: string;
            pm: string;
        };
        alphysY8B2: {
            author: string;
            pm: string;
        };
        alphysY8B3: {
            author: string;
            pm: string;
        };
        alphysY8B4a: {
            author: string;
            pm: string;
        };
        alphysY8B4b: {
            author: string;
            pm: string;
        };
        alphysY8B5: {
            author: string;
            pm: string;
        };
        alphysY8B6: {
            author: string;
            pm: string;
        };
        alphysY8B7: {
            author: string;
            pm: string;
        };
        alphysY8B8: {
            author: string;
            pm: string;
        };
        alphysY8B9: {
            author: string;
            pm: string;
        };
        alphysY8B10: {
            author: string;
            pm: string;
        };
        alphysY8B11: {
            author: string;
            pm: string;
        };
        alphysY8B12: {
            author: string;
            pm: string;
        };
        alphysY8B13: {
            author: string;
            pm: string;
        };
        alphysY8B14: {
            author: string;
            pm: string;
        };
        alphysY8B15: {
            author: string;
            pm: string;
        };
        alphysY8B16: {
            author: string;
            pm: string;
        };
        alphysY8B17: {
            author: string;
            pm: string;
        };
        alphysY8B18: {
            author: string;
            pm: string;
        };
        alphysY8B19: {
            author: string;
            pm: string;
        };
        alphysY8B20: {
            author: string;
            pm: string;
        };
        alphysY8C1: {
            author: string;
            pm: string;
        };
        alphysY8C2a: {
            author: string;
            pm: string;
        };
        alphysY8C2b: {
            author: string;
            pm: string;
        };
        alphysY8C2c: {
            author: string;
            pm: string;
        };
        alphysY8C3: {
            author: string;
            pm: string;
        };
        alphysY8C4: {
            author: string;
            pm: string;
        };
        alphysY8C5: {
            author: string;
            pm: string;
        };
        alphysY8C6: {
            author: string;
            pm: string;
        };
        alphysY8C7: {
            author: string;
            pm: string;
        };
        alphysY8D1a: {
            author: string;
            pm: string;
        };
        alphysY8D1b: {
            author: string;
            pm: string;
        };
        alphysY8D1x: {
            author: string;
            pm: string;
        };
        alphysY8D2a: {
            author: string;
            pm: string;
        };
        alphysY8D2b: {
            author: string;
            pm: string;
        };
        alphysY8D2x: {
            author: string;
            pm: string;
        };
        alphysY8D3: {
            author: string;
            pm: string;
        };
        alphysY8D3x: {
            author: string;
            pm: string;
        };
        alphysY8D4: {
            author: string;
            pm: string;
        };
        alphysY8D4x: {
            author: string;
            pm: string;
        };
        alphysY8D5: {
            author: string;
            pm: string;
        };
        alphysY8D6: {
            author: string;
            pm: string;
        };
        alphysY8D7: {
            author: string;
            pm: string;
        };
        alphysY8D8: {
            author: string;
            pm: string;
        };
        alphysY8D9: {
            author: string;
            pm: string;
        };
        alphysZ1: {
            author: string;
            pm: string;
        };
        alphysZ2: {
            author: string;
            pm: string;
        };
        alphysZ3: {
            author: string;
            pm: string;
        };
        alphysZ4: {
            author: string;
            pm: string;
        };
        alphysZ5: {
            author: string;
            pm: string;
        };
        alphysZ6: {
            author: string;
            pm: string;
        };
        alphysZ7: {
            author: string;
            pm: string;
        };
        alphysZ8: {
            author: string;
            pm: string;
        };
        alphysZ9: {
            author: string;
            pm: string;
        };
        alphysZ10: {
            author: string;
            pm: string;
        };
        alphysZ11: {
            author: string;
            pm: string;
        };
        alphysZ12: {
            author: string;
            pm: string;
        };
        alphysZ13: {
            author: string;
            pm: string;
        };
        alphysZ14: {
            author: string;
            pm: string;
        };
        alphysZ15: {
            author: string;
            pm: string;
        };
        alphysZ16: {
            author: string;
            pm: string;
        };
        alphysZ17: {
            author: string;
            pm: string;
        };
        alphysZ18: {
            author: string;
            pm: string;
        };
    };
    n_sidebarCellPms4: string;
    n_shop_bpants: {
        exit: () => string[];
        item: () => string[];
        itemInfo: () => string[];
        itemPrompt: () => "<09>{#p/monster}{#k/7}What do YOU want from me?" | "<09>{#p/monster}{#k/0}What do you want from me?";
        itemPurchase: () => string[];
        itemPurchasePrompt: string;
        itemUnavailable: () => "<09>{#p/monster}{#k/5}Sorry, that was one of a kind." | "<09>{#p/monster}{#k/4}Sorry, that was one of a kind.";
        menu: () => string[];
        menuPrompt1: () => "<23>{#p/monster}{#k/5}* Heyyyy little bully." | "<23>{#p/monster}{#k/5}* Heyyyy little murderer." | "<23>{#p/monster}{#k/0}* What can I do for you, little buddy?";
        menuPrompt2: () => "<23>{#p/monster}{#k/7}* Need anything else?" | "<23>{#p/monster}{#k/0}* Need anything else?";
        sell1: () => string[];
        sell2: string[];
        talk: () => string[];
        talkPrompt: () => "<09>{#p/monster}{#k/0}Take it from me, little bully." | "<09>{#p/monster}{#k/0}Take it from me, little murderer." | "<09>{#p/monster}{#k/0}Take it from me, little buddy.";
        talkText: (i: number) => string[];
    };
    n_shop_gossip: {
        exit: () => string[] | {
            b: string;
            c: string;
            s: boolean;
        }[];
        item: () => string[];
        itemInfo: string[];
        itemPrompt: string;
        itemPurchase: string[];
        itemPurchasePrompt: () => "Buy it for\n$(x)G?" | "Take it?";
        itemUnavailable: () => "<09>{#p/narrator}Nothing left." | "<09>{#p/monster}{#k/5/1}{@fill:#d4bbff}We're all sold out!\nMee-YOW!";
        menu: () => string[];
        menuPrompt1: string;
        menuPrompt2: string;
        menuPrompt3: () => "<23>{#p/narrator}* ...but everybody ran." | "<23>{#p/narrator}* ...but nobody came.";
        note: () => (string | {
            b: string;
            c: string;
            s?: undefined;
        } | {
            b: string;
            c: string;
            s: boolean;
        })[];
        sell1: () => string[] | {
            b: string;
            c: string;
        }[];
        sell2: () => string[] | ({
            b: string;
            c: string;
            s?: undefined;
        } | {
            b: string;
            c: string;
            s: boolean;
        })[];
        talk: () => string[];
        talkPrompt: string;
        talkText: (i: number) => (string | {
            b: string;
            c: string;
            s?: undefined;
        } | {
            b: string;
            c: string;
            s: boolean;
        })[];
        zeroPrompt: string;
    };
    p_alphys: Partial<CosmosKeyed<CosmosProvider<string[]>, string>>;
    s_save: {
        a_start: {
            name: string;
            text: () => string[];
        };
        a_path3: {
            name: string;
            text: string[];
        };
        a_elevator1: {
            name: string;
            text: () => string[];
        };
        a_mettaton2: {
            name: string;
            text: () => string[];
        };
        a_aftershow: {
            name: string;
            text: () => string[];
        };
        a_core_entry1: {
            name: string;
            text: string[];
        };
        a_core_checkpoint: {
            name: string;
            text: () => string[];
        };
    };
};
export default text;
