import { CosmosKeyed, CosmosProvider } from '../engine/utils';
export declare function areaKills(): number;
export declare function toriSV(): boolean;
export declare function toriCheck(): boolean;
declare const text: {
    a_outlands: {
        stargum1: string[];
        stargum2: string[];
        stargum3: string[];
        fireplace1: string[];
        fireplace2a: string[];
        fireplace2b: () => string[];
        fireplace2c: string[];
        fireplace2d: string[];
        noticereturn: string[];
        noticestart: string[];
        noticedummy: string[];
        afrog: {
            a: string[];
            b: string[];
        };
        asriel1: string[];
        asriel1b: string[];
        asriel2: string[];
        asriel2b: string[];
        asriel3: string[];
        asriel4: string[];
        asrielDiary: string[][];
        backdesk: {
            a: string[];
            b: string[];
            b2: string[];
        };
        bedfailToriel: string[];
        bedfailAsgore: string[];
        blooky1: string[];
        blooky2: string[];
        blooky3: string[];
        blooky4: string[];
        blooky5: string[];
        blooky6: string[];
        blooky7: string[];
        book1: string[];
        book2: string[];
        book3: string[];
        book4: string[];
        breakfast: string[];
        breakslow: string[];
        candy1: string[];
        candy2: string[];
        candy3: string[];
        candy4: string[];
        candy5: string[];
        candy6: string[];
        candy7: string[];
        candy8: string[];
        chair1a: string[];
        chair1b: string[];
        chair1c: string[];
        chair1d: string[];
        chair1e: string[];
        chair1f: (...args: any[]) => string[];
        chair2a1: string[];
        chair2a2: string[];
        chair2a3: string[];
        chair2a4: string[];
        chair2c1: string[];
        chair2c2: string[];
        chair2c3: string[];
        chair2c4: string[];
        chair2c5: string[];
        chair2c6: string[];
        chair2c7: string[];
        chair2c8: string[];
        chair2d1: string[];
        chair2d2: string[];
        chair2d3: string[];
        chair2d4: string[];
        chair2d5: string[];
        chair2d6: string[];
        chair3: string[];
        chair4: string[];
        closetrocket: {
            a: string[];
            b: string[];
            b2: string[];
            c: string[];
        };
        goner: {
            a1: string[];
            a2: string[];
        };
        cryme: {
            a: () => string[];
            b: (...args: any[]) => string[];
        };
        danger_puzzle1: string[];
        danger_puzzle2: string[];
        danger_puzzle3: string[];
        danger_puzzle4: string[];
        danger_puzzle5a: string[];
        danger_puzzle5b: string[];
        danger_puzzle5c: string[];
        danger_puzzle5d: string[];
        danger_puzzle5e: string[];
        danger_puzzle6: string[];
        danger_puzzle7: string[];
        denie: string[];
        dipper: {
            a: string[];
            b: string[];
        };
        doorRed: {
            a: string[];
            a2: string[];
            a3: () => string[];
            b: string[];
            c: string[];
            d: string[];
        };
        doorYellow: () => string[];
        drop_fail: string[];
        drop_pie: string[];
        drop_snails: string[];
        drop_soda: string[];
        drop_steak: string[];
        dummy1: string[];
        dummy2: string[];
        dummy3: string[];
        dummy4: string[];
        dummy5: string[];
        dummy6: string[];
        dummy7: string[];
        dummy8: string[];
        dummy9: string[];
        dummy9a: string[];
        dummy10: string[];
        dummy11: string[];
        dummy12: string[];
        eat_pie: string[];
        eat_snails: string[];
        eat_soda: string[];
        eat_steak: string[];
        endtwinkly1: string[];
        endtwinkly2: string[];
        endtwinklyA1: string[];
        endtwinklyA2: string[];
        endtwinklyAreaction: string[];
        endtwinklyB: string[];
        endtwinklyB2: string[];
        endtwinklyB3: string[];
        endtwinklyBA: () => string[];
        endtwinklyBB: string[];
        endtwinklyBBA: string[];
        endtwinklyBBB: string[];
        endtwinklyBC: string[];
        endtwinklyBD: string[];
        endtwinklyC: string[];
        endtwinklyD: string[];
        endtwinklyE: string[];
        endtwinklyEA: string[];
        endtwinklyEB: string[];
        endtwinklyF: string[];
        endtwinklyFA: string[];
        endtwinklyFB: string[];
        endtwinklyFXA: string[];
        endtwinklyG: string[];
        endtwinklyG1: string[];
        endtwinklyG2: string[];
        endtwinklyH: string[];
        endtwinklyI: string[];
        endtwinklyIA: string[];
        endtwinklyIB: string[];
        endtwinklyJ: string[];
        endtwinklyK: string[];
        endtwinklyK1: string[];
        endtwinklyK2: string[];
        endtwinklyKA: string[];
        endtwinklyKB: string[];
        endtwinklyKC: string[];
        endtwinklyKD: string[];
        endtwinklyL: string[];
        endtwinklyL1: string[];
        exit1: string[];
        exit2: () => string[];
        exit3: string[];
        exit4: string[];
        exitfail1: () => string[];
        food: () => string[];
        fridgetrap: {
            a: string[];
            b: string[];
            b1: string[];
            b2: string[];
            c: string[];
            d: string[];
        };
        front1: string[];
        front2: () => string[];
        front3: () => string[];
        front4: () => string[];
        goodbye1: string[];
        goodbye1a: string[];
        goodbye2: string[];
        goodbye3: string[];
        goodbye4: string[];
        goodbye5a: string[];
        goodbye5b: string[];
        guard: {
            a: () => string[];
        };
        halo: {
            a: string[];
            b: string[];
        };
        indie1: string[];
        indie1a: string[];
        indie1b: string[];
        indie2a: string[];
        indie2b: string[];
        indie2b1: string[];
        indie2c: string[];
        indie2d: string[];
        indie2e: string[];
        indie2f: string[];
        indie3a: string[];
        indie3b: string[];
        indie4: string[];
        indie5: string[][];
        indie6: string[];
        indie6a: string[];
        indie6b: string[];
        indie7: string[];
        indie8: string[];
        lobby_puzzle1: string[];
        lobby_puzzle2: string[];
        lobby_puzzle3: string[];
        loox: {
            a: string[];
            b: string[];
            c: string[];
            d: string[];
        };
        manana: {
            a: (...args: any[]) => string[];
            b: string[];
            c: string[];
            d: string[];
            e: string[];
            f: string[];
        };
        patron: {
            a: () => string[];
        };
        pie: () => string[];
        plot_call: {
            a: string[];
            b: () => string[];
            b1: string[];
            b2: string[];
            c: string[];
            d: string[];
        };
        puzzle1A: string[];
        puzzle3A: string[];
        return1: string[];
        return2a: string[];
        return2b: string[];
        return2c: string[];
        return2d: string[];
        return2e: string[];
        return3: string[];
        return4: () => string[];
        return5: string[];
        return6: string[];
        runaway1: string[][];
        runaway2: string[];
        silencio: {
            a: (...args: any[]) => string[];
            b: (...args: any[]) => string[];
        };
        socks1: () => string[];
        socks2: () => string[];
        socks3: string[];
        socks4: string[];
        socks5: string[];
        socks6: string[];
        socks7: string[];
        soupguy: {
            a: (...args: any[]) => string[];
            b: (...args: any[]) => string[];
            c: (...args: any[]) => string[];
        };
        steaksale: {
            a: (...args: any[]) => string[];
            a1: string[];
            b: string[];
            b1: (...args: any[]) => string[];
            b2: string[];
            c: string[];
            c1: (...args: any[]) => string[];
            c2: string[];
            d: (...args: any[]) => string[];
            e: (...args: any[]) => string[];
            f: string[];
            g: string[];
            h: string[];
            i: string[];
        };
        supervisor: {
            a: (...args: any[]) => string[];
            a2: string[];
            a3: string[];
            a4: string[];
            a5: (...args: any[]) => string[];
            aa: string[];
            aa1: string[][];
            aa1a: string[];
            aa1b: string[];
            aa1c: string[];
            ab: string[];
            b: string[];
            c: string[][];
            d: string[];
            e: string[];
        };
        terminal: {
            a: string[];
            b: string[];
            c: () => string[];
            d: () => string[];
        };
        torieldanger: {
            a: string[];
            b: string[];
        };
        latetoriel1: string[];
        latetoriel2: string[];
        trivia: {
            w_backstage_cabinet: () => string[];
            w_backstage_coatrack: string[];
            w_candy: string[];
            w_clay: string[];
            w_danger1: string[];
            w_djtable: string[];
            w_doorBlue: () => string[];
            w_doorCyan: () => string[];
            w_doorGreen: () => string[];
            w_doorOrange: () => string[];
            w_doorPurple: () => string[];
            w_froggit: string[];
            w_froggit_view: string[];
            w_froggit1: string[];
            w_kitchenwall: string[];
            w_lobby1: string[];
            w_pacing_view: string[];
            w_pacing1: string[];
            w_pacing2: string[];
            w_pacing3: string[];
            w_puzzle1_view: string[];
            w_puzzle2: string[];
            w_puzzle3_view: string[];
            w_puzzle4: string[];
            w_restricted1: string[];
            w_ta_box: string[];
            w_ta_cabinet: string[];
            w_ta_chest: () => string[];
            w_ta_frame: string[];
            w_ta_paper: string[];
            w_tf_bookshelf: () => string[];
            w_tf_couch: () => string[];
            w_tf_table: string[];
            w_tf_window: string[];
            w_th_door: string[];
            w_th_mirror: () => string[];
            w_th_plant: () => string[];
            w_th_sausage: string[];
            w_th_table1: string[];
            w_th_table2: string[];
            w_tk_counter: () => string[];
            w_tk_sink: string[];
            w_tk_stove: string[];
            w_tk_trash: string[];
            w_tl_azzychair: () => string[];
            w_tl_bookshelf: () => string[];
            w_tl_goreychair: string[];
            w_tl_table: string[];
            w_tl_tools: string[];
            w_tl_torichair: string[];
            w_toriel_toriel: () => string[];
            w_tt_bed: string[];
            w_tt_bookshelf: () => string[];
            w_tt_cactus: string[];
            w_tt_chair: string[];
            w_tt_diary: (...args: any[]) => string[];
            w_tt_plant: string[];
            w_tt_trash: () => string[];
            w_tutorial_view: string[];
            w_tutorial1: () => string[];
            w_wreckage: () => string[];
        };
        piecheck: () => string[];
        piesmash1: string[];
        piesmash2: string[];
        piesmash3: string[];
        tutorial_puzzle1: string[];
        tutorial_puzzle2: string[];
        tutorial_puzzle2a: string[];
        tutorial_puzzle3: string[];
        tutorial_puzzle4: string[];
        tutorial_puzzle4a: string[];
        tutorial_puzzle5: string[];
        tutorial_puzzle6: string[];
        tutorial_puzzle7: string[];
        tutorial_puzzle8: string[];
        twinkly1: string[];
        twinkly2: string[];
        twinkly3: string[];
        twinkly4: string[];
        twinkly5: string[];
        twinkly6: string[];
        twinkly6a: string[];
        twinkly7: string[];
        twinkly8: string[];
        twinkly9: string[];
        twinkly9a: string[];
        twinkly9a1: string[];
        twinkly9a2: string[];
        twinkly9a3: string[];
        twinkly9a4: string[];
        twinkly9a5: string[];
        twinkly9a6: never[];
        twinkly9a7: never[];
        twinkly9a8: string[];
        twinkly10: string[];
        twinkly11: string[];
        twinkly12: string[];
        twinkly13: string[];
        twinkly14: string;
        twinkly15: string[];
        twinkly16: string[];
        twinkly17: string[];
        twinkly18: string[];
        twinkly19: string[];
        twinkly20: string[];
        twinkly21: string[];
        twinkly22: string[];
        w_coffin1: () => string[];
        w_coffin2: (...args: any[]) => string[];
        w_coffin3: string[];
        w_coffin4: string[];
        w_coffin5: string[];
        w_dummy1: string[];
        wonder1: string[];
        wonder2: string[];
        wonder3: string[];
        wonder4: string[];
        wonder5: string[];
        wonder6: string[];
    };
    b_group_froggitWhimsun: string[];
    b_group_froggitWhimsun2a: string[];
    b_group_froggitWhimsun2b: string[];
    b_group_looxMigospMushy: string[];
    b_group_looxMigospMushy2: string[];
    b_group_looxMigospMushy3: string[];
    b_group_moldsmalMigosp: string[];
    b_opponent_froggit: {
        act_check: string[];
        act_compliment: string[];
        act_flirt: string[];
        act_translate0: string[];
        act_translate1: string[];
        act_translate2: string[];
        confuseText: string[];
        flirtText: string[];
        idleText1: string[];
        idleText2: string[];
        idleText3: string[];
        idleText4: string[];
        mercyStatus: string[];
        name: string;
        niceText: string[];
        perilStatus: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
    };
    b_opponent_whimsun: {
        act_check: string[];
        act_console: string[];
        act_flirt: string[];
        act_terrorize: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        name: string;
        perilStatus: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        status5: string[];
        status6: string[];
    };
    b_opponent_loox: {
        act_check: string[];
        act_dontpick: string[];
        act_flirt: string[];
        act_pick: string[];
        checkTalk1: string[];
        dontDeny1: string[];
        dontTalk1: string[];
        flirtDeny1: string[];
        flirtTalk1: string[];
        hurtStatus: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        idleTalk4: string[];
        idleTalk5: string[];
        name: string;
        pickTalk1: string[];
        spareStatus: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        status5: string[];
        status6: string[];
        status7: string[];
    };
    b_opponent_migosp: {
        act_check: string[];
        act_flirt: string[];
        act_talk: string[];
        flirtTalk: string[];
        groupInsult: string[];
        groupStatus1: string[];
        groupStatus2: string[];
        groupTalk1: string[];
        groupTalk2: string[];
        groupTalk3: string[];
        groupTalk4: string[];
        groupTalk5: string[];
        groupTalk6: string[];
        name: string;
        perilStatus: string[];
        soloInsult: string[];
        soloStatus: string[];
        soloTalk1: string[];
        soloTalk2: string[];
        soloTalk3: string[];
        soloTalk4: string[];
        soloTalk5: string[];
        talkTalk: string[];
    };
    b_opponent_mushy: {
        act_challenge: string[];
        act_check: string[];
        act_flirt: string[];
        act_taunt: string[];
        challengeStatus: string[];
        challengeTalk1: string[];
        challengeTalk2: string[];
        flirtStatus1: string[];
        flirtTalk1: string[];
        hurtStatus: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        name: string;
        spareStatus: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        status5: string[];
        tauntStatus1: string[];
        tauntTalk1: string[];
    };
    b_opponent_napstablook: {
        act_check: string[];
        awkwardTalk: string[];
        checkTalk: string[];
        cheer0: string[];
        cheer1: string[];
        cheer2: string[];
        cheer3: string[];
        cheerTalk1: string[];
        cheerTalk2: string[];
        cheerTalk3: string[];
        cheerTalk4: string[];
        consoleTalk1: string[];
        consoleTalk2: string[];
        consoleTalk3: string[];
        critic1: string[];
        criticTalk: string[];
        deadTalk: string[];
        flirt0: string[];
        flirt1: string[];
        flirt2: string[];
        flirt3: string[];
        flirt4: string[];
        flirtTalk1: string[];
        flirtTalk2: string[];
        flirtTalk3: string[];
        flirtTalk4: string[];
        idleTalk1: string[];
        idleTalk2: string[];
        idleTalk3: string[];
        insultTalk1: string[];
        insultTalk2: string[];
        insultTalk3: string[];
        insultTalk4: string[];
        name: string;
        silentTalk: string[];
        sincere: string[];
        sincereTalk: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status3a: string[];
        status4: string[];
        status5: string[];
        status5a: string[];
        status6: string[];
        status7: string[];
        status8: string[];
        status9: string[];
        status10: string[];
        suck: string[];
        talk0: string[];
        talk1: string[];
        talk2: string[];
        talk3: string[];
        talk4: string[];
        talk5: string[];
        talk6: string[];
        talk7: string[];
        talkTalk1: string[];
        talkTalk2: string[];
        talkTalk3: string[];
        talkTalk4: string[];
        talkTalk5: string[];
        talkTalk6: string[];
        talkTalk7: string[];
        talkTalk8: string[];
        talkTalk9: string[];
        threat: string[];
    };
    b_opponent_toriel: {
        spannerText: string[];
        spannerTalk: string[];
        spannerTalkRepeat: string[];
        act_check: string[];
        criminal1: string[];
        criminal2: string[];
        criminal3: string[];
        cutscene1: string[];
        cutscene2: string[];
        death1: string[];
        death2: string[];
        death3: string[];
        magic1: string[];
        magic2: string[];
        name: string;
        spareTalk1: string[];
        spareTalk2: string[];
        spareTalk3: string[];
        spareTalk4: string[];
        spareTalk5: string[];
        spareTalk6: string[];
        spareTalk7: string[];
        spareTalk8: string[];
        spareTalk9: string[];
        spareTalk10: string[];
        spareTalk11: string[];
        spareTalk12: string[];
        spareTalk13: string[];
        spareTalk14: string[];
        spareTalk15: string[];
        spareTalk16: string[];
        spareTalk17: string[];
        spareTalk18: string[];
        spareTalk19: string[];
        spareTalk20: string[];
        spareTalk21: string[];
        spareTalk22: string[];
        spareTalk23: string[];
        spareTalk24: string[];
        spareTalk28a: string[];
        spareTalk28b: string[];
        spareTalk28c: string[];
        status1: string[];
        status2: string[];
        status3: string[];
        status4: string[];
        status5: string[];
        talk0: string[];
        talk1: string[];
        talk2: string[];
        talk3: string[];
        talk4: string[];
        talk5: string[];
        talk6: string[];
        assistStatus: string[];
        talk7: string[];
        talk8: string[];
        theft: string[];
    };
    c_about1: string[];
    c_about2: string[];
    c_name_hello: string;
    c_name_about: string;
    c_name_mom: string;
    c_name_flirt: string;
    c_name_toriel: string;
    c_name_puzzle: string;
    c_flirt1: string[];
    c_flirt2: string[];
    c_flirt3: string[];
    c_hello: string[][];
    c_mom1: string[];
    c_mom2: string[];
    c_mom3: string[];
    c_puzzle1: string[];
    i_candy: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_chocolate: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_delta: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_halo: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_little_dipper: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_pie: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_pie2: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_pie3: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_snails: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_soda: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_spacesuit: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    i_spanner: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_starbertA: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_starbertB: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_starbertC: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: () => string[];
    };
    i_steak: {
        battle: {
            description: string;
            name: string;
        };
        drop: string[];
        info: string[];
        name: string;
        use: string[];
    };
    p_toriel: Partial<CosmosKeyed<CosmosProvider<string[]>, string>>;
    s_save: {
        w_courtyard: {
            name: string;
            text: () => string[];
        };
        w_entrance: {
            name: string;
            text: () => string[];
        };
        w_froggit: {
            name: string;
            text: () => string[];
        };
        w_mouse: {
            name: string;
            text: () => string[];
        };
        w_start: {
            name: string;
            text: never[];
        };
    };
};
export default text;
